/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CustomerSummaryRequest } from '../model';
// @ts-ignore
import type { CustomerSummaryResponse } from '../model';
// @ts-ignore
import type { HTTPValidationError } from '../model';
// @ts-ignore
import type { SalesHistoryRequest } from '../model';
// @ts-ignore
import type { SalesHistoryResponse } from '../model';
/**
 * CustomerDetailApi - axios parameter creator
 * @export
 */
export const CustomerDetailApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 고객 요약 정보 조회  테이블에서 행 클릭 시 표시되는 모달의 요약 탭 정보  - **company_id**: 조회할 고객사 ID - **dateRange**: 조회 기간 (startDate ~ endDate)     - startDate: 전기(previous) 기준점 (YYYY-MM-DD)     - endDate: 현재(current) 기준점 (YYYY-MM-DD)  Returns:     CustomerSummaryResponse:         - companyId: 고객사 ID         - companyName: 고객사명         - manager: 담당자명         - category: 카테고리 (recruit/performance/public)         - companySize: 기업 규모 (T0~T10)         - productUsage: 사용 중인 제품 목록         - contractAmount: 계약금액 (원 단위)         - current: 현재 시점 데이터         - previous: 전기(과거) 시점 데이터
         * @summary Get Customer Summary
         * @param {number} companyId 
         * @param {CustomerSummaryRequest} customerSummaryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCustomerSummaryApiV1DashboardCustomerCompanyIdSummaryPost: async (companyId: number, customerSummaryRequest: CustomerSummaryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyId' is not null or undefined
            assertParamExists('getCustomerSummaryApiV1DashboardCustomerCompanyIdSummaryPost', 'companyId', companyId)
            // verify required parameter 'customerSummaryRequest' is not null or undefined
            assertParamExists('getCustomerSummaryApiV1DashboardCustomerCompanyIdSummaryPost', 'customerSummaryRequest', customerSummaryRequest)
            const localVarPath = `/api/v1/dashboard/customer/{company_id}/summary`
                .replace(`{${"company_id"}}`, encodeURIComponent(String(companyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(customerSummaryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 영업 히스토리 조회  테이블에서 행 클릭 시 표시되는 모달의 영업 히스토리 탭 정보  - **company_id**: 조회할 고객사 ID - **dateRange**: 조회 기간 (startDate ~ endDate)     - startDate: 조회 시작일 (YYYY-MM-DD)     - endDate: 조회 종료일 (YYYY-MM-DD)     - 해당 기간 내의 영업 액션만 반환  Returns:     SalesHistoryResponse:         - companyId: 고객사 ID         - companyName: 고객사명         - salesActions: 영업 액션 목록 (최신순)
         * @summary Get Sales History
         * @param {number} companyId 
         * @param {SalesHistoryRequest} salesHistoryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSalesHistoryApiV1DashboardCustomerCompanyIdSalesHistoryPost: async (companyId: number, salesHistoryRequest: SalesHistoryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyId' is not null or undefined
            assertParamExists('getSalesHistoryApiV1DashboardCustomerCompanyIdSalesHistoryPost', 'companyId', companyId)
            // verify required parameter 'salesHistoryRequest' is not null or undefined
            assertParamExists('getSalesHistoryApiV1DashboardCustomerCompanyIdSalesHistoryPost', 'salesHistoryRequest', salesHistoryRequest)
            const localVarPath = `/api/v1/dashboard/customer/{company_id}/sales-history`
                .replace(`{${"company_id"}}`, encodeURIComponent(String(companyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(salesHistoryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CustomerDetailApi - functional programming interface
 * @export
 */
export const CustomerDetailApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CustomerDetailApiAxiosParamCreator(configuration)
    return {
        /**
         * 고객 요약 정보 조회  테이블에서 행 클릭 시 표시되는 모달의 요약 탭 정보  - **company_id**: 조회할 고객사 ID - **dateRange**: 조회 기간 (startDate ~ endDate)     - startDate: 전기(previous) 기준점 (YYYY-MM-DD)     - endDate: 현재(current) 기준점 (YYYY-MM-DD)  Returns:     CustomerSummaryResponse:         - companyId: 고객사 ID         - companyName: 고객사명         - manager: 담당자명         - category: 카테고리 (recruit/performance/public)         - companySize: 기업 규모 (T0~T10)         - productUsage: 사용 중인 제품 목록         - contractAmount: 계약금액 (원 단위)         - current: 현재 시점 데이터         - previous: 전기(과거) 시점 데이터
         * @summary Get Customer Summary
         * @param {number} companyId 
         * @param {CustomerSummaryRequest} customerSummaryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCustomerSummaryApiV1DashboardCustomerCompanyIdSummaryPost(companyId: number, customerSummaryRequest: CustomerSummaryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CustomerSummaryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCustomerSummaryApiV1DashboardCustomerCompanyIdSummaryPost(companyId, customerSummaryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CustomerDetailApi.getCustomerSummaryApiV1DashboardCustomerCompanyIdSummaryPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 영업 히스토리 조회  테이블에서 행 클릭 시 표시되는 모달의 영업 히스토리 탭 정보  - **company_id**: 조회할 고객사 ID - **dateRange**: 조회 기간 (startDate ~ endDate)     - startDate: 조회 시작일 (YYYY-MM-DD)     - endDate: 조회 종료일 (YYYY-MM-DD)     - 해당 기간 내의 영업 액션만 반환  Returns:     SalesHistoryResponse:         - companyId: 고객사 ID         - companyName: 고객사명         - salesActions: 영업 액션 목록 (최신순)
         * @summary Get Sales History
         * @param {number} companyId 
         * @param {SalesHistoryRequest} salesHistoryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSalesHistoryApiV1DashboardCustomerCompanyIdSalesHistoryPost(companyId: number, salesHistoryRequest: SalesHistoryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SalesHistoryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSalesHistoryApiV1DashboardCustomerCompanyIdSalesHistoryPost(companyId, salesHistoryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CustomerDetailApi.getSalesHistoryApiV1DashboardCustomerCompanyIdSalesHistoryPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CustomerDetailApi - factory interface
 * @export
 */
export const CustomerDetailApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CustomerDetailApiFp(configuration)
    return {
        /**
         * 고객 요약 정보 조회  테이블에서 행 클릭 시 표시되는 모달의 요약 탭 정보  - **company_id**: 조회할 고객사 ID - **dateRange**: 조회 기간 (startDate ~ endDate)     - startDate: 전기(previous) 기준점 (YYYY-MM-DD)     - endDate: 현재(current) 기준점 (YYYY-MM-DD)  Returns:     CustomerSummaryResponse:         - companyId: 고객사 ID         - companyName: 고객사명         - manager: 담당자명         - category: 카테고리 (recruit/performance/public)         - companySize: 기업 규모 (T0~T10)         - productUsage: 사용 중인 제품 목록         - contractAmount: 계약금액 (원 단위)         - current: 현재 시점 데이터         - previous: 전기(과거) 시점 데이터
         * @summary Get Customer Summary
         * @param {CustomerDetailApiGetCustomerSummaryApiV1DashboardCustomerCompanyIdSummaryPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCustomerSummaryApiV1DashboardCustomerCompanyIdSummaryPost(requestParameters: CustomerDetailApiGetCustomerSummaryApiV1DashboardCustomerCompanyIdSummaryPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<CustomerSummaryResponse> {
            return localVarFp.getCustomerSummaryApiV1DashboardCustomerCompanyIdSummaryPost(requestParameters.companyId, requestParameters.customerSummaryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 영업 히스토리 조회  테이블에서 행 클릭 시 표시되는 모달의 영업 히스토리 탭 정보  - **company_id**: 조회할 고객사 ID - **dateRange**: 조회 기간 (startDate ~ endDate)     - startDate: 조회 시작일 (YYYY-MM-DD)     - endDate: 조회 종료일 (YYYY-MM-DD)     - 해당 기간 내의 영업 액션만 반환  Returns:     SalesHistoryResponse:         - companyId: 고객사 ID         - companyName: 고객사명         - salesActions: 영업 액션 목록 (최신순)
         * @summary Get Sales History
         * @param {CustomerDetailApiGetSalesHistoryApiV1DashboardCustomerCompanyIdSalesHistoryPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSalesHistoryApiV1DashboardCustomerCompanyIdSalesHistoryPost(requestParameters: CustomerDetailApiGetSalesHistoryApiV1DashboardCustomerCompanyIdSalesHistoryPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<SalesHistoryResponse> {
            return localVarFp.getSalesHistoryApiV1DashboardCustomerCompanyIdSalesHistoryPost(requestParameters.companyId, requestParameters.salesHistoryRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getCustomerSummaryApiV1DashboardCustomerCompanyIdSummaryPost operation in CustomerDetailApi.
 * @export
 * @interface CustomerDetailApiGetCustomerSummaryApiV1DashboardCustomerCompanyIdSummaryPostRequest
 */
export interface CustomerDetailApiGetCustomerSummaryApiV1DashboardCustomerCompanyIdSummaryPostRequest {
    /**
     * 
     * @type {number}
     * @memberof CustomerDetailApiGetCustomerSummaryApiV1DashboardCustomerCompanyIdSummaryPost
     */
    readonly companyId: number

    /**
     * 
     * @type {CustomerSummaryRequest}
     * @memberof CustomerDetailApiGetCustomerSummaryApiV1DashboardCustomerCompanyIdSummaryPost
     */
    readonly customerSummaryRequest: CustomerSummaryRequest
}

/**
 * Request parameters for getSalesHistoryApiV1DashboardCustomerCompanyIdSalesHistoryPost operation in CustomerDetailApi.
 * @export
 * @interface CustomerDetailApiGetSalesHistoryApiV1DashboardCustomerCompanyIdSalesHistoryPostRequest
 */
export interface CustomerDetailApiGetSalesHistoryApiV1DashboardCustomerCompanyIdSalesHistoryPostRequest {
    /**
     * 
     * @type {number}
     * @memberof CustomerDetailApiGetSalesHistoryApiV1DashboardCustomerCompanyIdSalesHistoryPost
     */
    readonly companyId: number

    /**
     * 
     * @type {SalesHistoryRequest}
     * @memberof CustomerDetailApiGetSalesHistoryApiV1DashboardCustomerCompanyIdSalesHistoryPost
     */
    readonly salesHistoryRequest: SalesHistoryRequest
}

/**
 * CustomerDetailApi - object-oriented interface
 * @export
 * @class CustomerDetailApi
 * @extends {BaseAPI}
 */
export class CustomerDetailApi extends BaseAPI {
    /**
     * 고객 요약 정보 조회  테이블에서 행 클릭 시 표시되는 모달의 요약 탭 정보  - **company_id**: 조회할 고객사 ID - **dateRange**: 조회 기간 (startDate ~ endDate)     - startDate: 전기(previous) 기준점 (YYYY-MM-DD)     - endDate: 현재(current) 기준점 (YYYY-MM-DD)  Returns:     CustomerSummaryResponse:         - companyId: 고객사 ID         - companyName: 고객사명         - manager: 담당자명         - category: 카테고리 (recruit/performance/public)         - companySize: 기업 규모 (T0~T10)         - productUsage: 사용 중인 제품 목록         - contractAmount: 계약금액 (원 단위)         - current: 현재 시점 데이터         - previous: 전기(과거) 시점 데이터
     * @summary Get Customer Summary
     * @param {CustomerDetailApiGetCustomerSummaryApiV1DashboardCustomerCompanyIdSummaryPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomerDetailApi
     */
    public getCustomerSummaryApiV1DashboardCustomerCompanyIdSummaryPost(requestParameters: CustomerDetailApiGetCustomerSummaryApiV1DashboardCustomerCompanyIdSummaryPostRequest, options?: RawAxiosRequestConfig) {
        return CustomerDetailApiFp(this.configuration).getCustomerSummaryApiV1DashboardCustomerCompanyIdSummaryPost(requestParameters.companyId, requestParameters.customerSummaryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 영업 히스토리 조회  테이블에서 행 클릭 시 표시되는 모달의 영업 히스토리 탭 정보  - **company_id**: 조회할 고객사 ID - **dateRange**: 조회 기간 (startDate ~ endDate)     - startDate: 조회 시작일 (YYYY-MM-DD)     - endDate: 조회 종료일 (YYYY-MM-DD)     - 해당 기간 내의 영업 액션만 반환  Returns:     SalesHistoryResponse:         - companyId: 고객사 ID         - companyName: 고객사명         - salesActions: 영업 액션 목록 (최신순)
     * @summary Get Sales History
     * @param {CustomerDetailApiGetSalesHistoryApiV1DashboardCustomerCompanyIdSalesHistoryPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomerDetailApi
     */
    public getSalesHistoryApiV1DashboardCustomerCompanyIdSalesHistoryPost(requestParameters: CustomerDetailApiGetSalesHistoryApiV1DashboardCustomerCompanyIdSalesHistoryPostRequest, options?: RawAxiosRequestConfig) {
        return CustomerDetailApiFp(this.configuration).getSalesHistoryApiV1DashboardCustomerCompanyIdSalesHistoryPost(requestParameters.companyId, requestParameters.salesHistoryRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

