/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DashboardTableRequest } from '../model';
// @ts-ignore
import type { DashboardTableResponse } from '../model';
// @ts-ignore
import type { HTTPValidationError } from '../model';
/**
 * DashboardApi - axios parameter creator
 * @export
 */
export const DashboardApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 고객사 파이프라인 현황 테이블 조회  복합 필터링, 정렬, 페이지네이션을 지원합니다.  - **dateRange**: 날짜 범위 (startDate ~ endDate, YYYY-MM-DD)     - startDate: 전기(previous) 기준점     - endDate: 현재(current) 기준점 - **search**: 기업명 부분 검색 - **filters**: 다중 선택 필터 (기업규모, 담당자, 카테고리, 제품 등) - **sort**: 정렬 필드와 방향 - **pagination**: 페이지 번호와 페이지 크기  Returns:     rows: 테이블 행 데이터 (productUsage, lastMBMDate, lastContactDate 포함)     total: 전체 건수     currentPage: 현재 페이지     pageSize: 페이지 크기
         * @summary Get Dashboard Companies
         * @param {DashboardTableRequest} dashboardTableRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDashboardCompaniesApiV1DashboardCompaniesPost: async (dashboardTableRequest: DashboardTableRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dashboardTableRequest' is not null or undefined
            assertParamExists('getDashboardCompaniesApiV1DashboardCompaniesPost', 'dashboardTableRequest', dashboardTableRequest)
            const localVarPath = `/api/v1/dashboard/companies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(dashboardTableRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 대시보드 필터 옵션 조회  사용 가능한 필터 값 목록을 반환합니다.  Returns:     managers: 담당자 목록     companySizes: 사용 중인 기업 규모 목록     categories: 사용 중인 카테고리 목록
         * @summary Get Filter Options
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFilterOptionsApiV1DashboardCompaniesFiltersGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/dashboard/companies/filters`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DashboardApi - functional programming interface
 * @export
 */
export const DashboardApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DashboardApiAxiosParamCreator(configuration)
    return {
        /**
         * 고객사 파이프라인 현황 테이블 조회  복합 필터링, 정렬, 페이지네이션을 지원합니다.  - **dateRange**: 날짜 범위 (startDate ~ endDate, YYYY-MM-DD)     - startDate: 전기(previous) 기준점     - endDate: 현재(current) 기준점 - **search**: 기업명 부분 검색 - **filters**: 다중 선택 필터 (기업규모, 담당자, 카테고리, 제품 등) - **sort**: 정렬 필드와 방향 - **pagination**: 페이지 번호와 페이지 크기  Returns:     rows: 테이블 행 데이터 (productUsage, lastMBMDate, lastContactDate 포함)     total: 전체 건수     currentPage: 현재 페이지     pageSize: 페이지 크기
         * @summary Get Dashboard Companies
         * @param {DashboardTableRequest} dashboardTableRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDashboardCompaniesApiV1DashboardCompaniesPost(dashboardTableRequest: DashboardTableRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DashboardTableResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDashboardCompaniesApiV1DashboardCompaniesPost(dashboardTableRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DashboardApi.getDashboardCompaniesApiV1DashboardCompaniesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 대시보드 필터 옵션 조회  사용 가능한 필터 값 목록을 반환합니다.  Returns:     managers: 담당자 목록     companySizes: 사용 중인 기업 규모 목록     categories: 사용 중인 카테고리 목록
         * @summary Get Filter Options
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFilterOptionsApiV1DashboardCompaniesFiltersGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFilterOptionsApiV1DashboardCompaniesFiltersGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DashboardApi.getFilterOptionsApiV1DashboardCompaniesFiltersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DashboardApi - factory interface
 * @export
 */
export const DashboardApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DashboardApiFp(configuration)
    return {
        /**
         * 고객사 파이프라인 현황 테이블 조회  복합 필터링, 정렬, 페이지네이션을 지원합니다.  - **dateRange**: 날짜 범위 (startDate ~ endDate, YYYY-MM-DD)     - startDate: 전기(previous) 기준점     - endDate: 현재(current) 기준점 - **search**: 기업명 부분 검색 - **filters**: 다중 선택 필터 (기업규모, 담당자, 카테고리, 제품 등) - **sort**: 정렬 필드와 방향 - **pagination**: 페이지 번호와 페이지 크기  Returns:     rows: 테이블 행 데이터 (productUsage, lastMBMDate, lastContactDate 포함)     total: 전체 건수     currentPage: 현재 페이지     pageSize: 페이지 크기
         * @summary Get Dashboard Companies
         * @param {DashboardApiGetDashboardCompaniesApiV1DashboardCompaniesPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDashboardCompaniesApiV1DashboardCompaniesPost(requestParameters: DashboardApiGetDashboardCompaniesApiV1DashboardCompaniesPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<DashboardTableResponse> {
            return localVarFp.getDashboardCompaniesApiV1DashboardCompaniesPost(requestParameters.dashboardTableRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 대시보드 필터 옵션 조회  사용 가능한 필터 값 목록을 반환합니다.  Returns:     managers: 담당자 목록     companySizes: 사용 중인 기업 규모 목록     categories: 사용 중인 카테고리 목록
         * @summary Get Filter Options
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFilterOptionsApiV1DashboardCompaniesFiltersGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getFilterOptionsApiV1DashboardCompaniesFiltersGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getDashboardCompaniesApiV1DashboardCompaniesPost operation in DashboardApi.
 * @export
 * @interface DashboardApiGetDashboardCompaniesApiV1DashboardCompaniesPostRequest
 */
export interface DashboardApiGetDashboardCompaniesApiV1DashboardCompaniesPostRequest {
    /**
     * 
     * @type {DashboardTableRequest}
     * @memberof DashboardApiGetDashboardCompaniesApiV1DashboardCompaniesPost
     */
    readonly dashboardTableRequest: DashboardTableRequest
}

/**
 * DashboardApi - object-oriented interface
 * @export
 * @class DashboardApi
 * @extends {BaseAPI}
 */
export class DashboardApi extends BaseAPI {
    /**
     * 고객사 파이프라인 현황 테이블 조회  복합 필터링, 정렬, 페이지네이션을 지원합니다.  - **dateRange**: 날짜 범위 (startDate ~ endDate, YYYY-MM-DD)     - startDate: 전기(previous) 기준점     - endDate: 현재(current) 기준점 - **search**: 기업명 부분 검색 - **filters**: 다중 선택 필터 (기업규모, 담당자, 카테고리, 제품 등) - **sort**: 정렬 필드와 방향 - **pagination**: 페이지 번호와 페이지 크기  Returns:     rows: 테이블 행 데이터 (productUsage, lastMBMDate, lastContactDate 포함)     total: 전체 건수     currentPage: 현재 페이지     pageSize: 페이지 크기
     * @summary Get Dashboard Companies
     * @param {DashboardApiGetDashboardCompaniesApiV1DashboardCompaniesPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApi
     */
    public getDashboardCompaniesApiV1DashboardCompaniesPost(requestParameters: DashboardApiGetDashboardCompaniesApiV1DashboardCompaniesPostRequest, options?: RawAxiosRequestConfig) {
        return DashboardApiFp(this.configuration).getDashboardCompaniesApiV1DashboardCompaniesPost(requestParameters.dashboardTableRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 대시보드 필터 옵션 조회  사용 가능한 필터 값 목록을 반환합니다.  Returns:     managers: 담당자 목록     companySizes: 사용 중인 기업 규모 목록     categories: 사용 중인 카테고리 목록
     * @summary Get Filter Options
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApi
     */
    public getFilterOptionsApiV1DashboardCompaniesFiltersGet(options?: RawAxiosRequestConfig) {
        return DashboardApiFp(this.configuration).getFilterOptionsApiV1DashboardCompaniesFiltersGet(options).then((request) => request(this.axios, this.basePath));
    }
}

