/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HTTPValidationError } from '../model';
/**
 * DealStagesApi - axios parameter creator
 * @export
 */
export const DealStagesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Deal Stage 히스토리 데이터 조회  기업별 Deal의 Stage 변화 히스토리를 타임라인 형식으로 반환: - Company → Leads → Deal_Contacts → Deals → Deal_Stage_History 경로로 조회 - 각 Deal의 Stage 전환 이력 및 체류 기간 포함 - pipeline_ids로 특정 파이프라인의 Deal만 필터링 가능 - owner_ids로 특정 영업담당자의 Deal만 필터링 가능
         * @summary Get Deal Stages
         * @param {string | null} [startDate] 시작일 (YYYY-MM-DD)
         * @param {string | null} [endDate] 종료일 (YYYY-MM-DD)
         * @param {string | null} [companyIds] 기업 ID 목록 (콤마 구분)
         * @param {string | null} [listIds] 리스트 ID 목록 (콤마 구분)
         * @param {string | null} [pipelineIds] 파이프라인 ID 목록 (콤마 구분)
         * @param {string | null} [ownerIds] 영업담당자 ID 목록 (콤마 구분)
         * @param {number} [limit] 최대 기업 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDealStagesApiV1DealStagesGet: async (startDate?: string | null, endDate?: string | null, companyIds?: string | null, listIds?: string | null, pipelineIds?: string | null, ownerIds?: string | null, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/deal-stages`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (startDate !== undefined) {
                localVarQueryParameter['start_date'] = startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['end_date'] = endDate;
            }

            if (companyIds !== undefined) {
                localVarQueryParameter['company_ids'] = companyIds;
            }

            if (listIds !== undefined) {
                localVarQueryParameter['list_ids'] = listIds;
            }

            if (pipelineIds !== undefined) {
                localVarQueryParameter['pipeline_ids'] = pipelineIds;
            }

            if (ownerIds !== undefined) {
                localVarQueryParameter['owner_ids'] = ownerIds;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DealStagesApi - functional programming interface
 * @export
 */
export const DealStagesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DealStagesApiAxiosParamCreator(configuration)
    return {
        /**
         * Deal Stage 히스토리 데이터 조회  기업별 Deal의 Stage 변화 히스토리를 타임라인 형식으로 반환: - Company → Leads → Deal_Contacts → Deals → Deal_Stage_History 경로로 조회 - 각 Deal의 Stage 전환 이력 및 체류 기간 포함 - pipeline_ids로 특정 파이프라인의 Deal만 필터링 가능 - owner_ids로 특정 영업담당자의 Deal만 필터링 가능
         * @summary Get Deal Stages
         * @param {string | null} [startDate] 시작일 (YYYY-MM-DD)
         * @param {string | null} [endDate] 종료일 (YYYY-MM-DD)
         * @param {string | null} [companyIds] 기업 ID 목록 (콤마 구분)
         * @param {string | null} [listIds] 리스트 ID 목록 (콤마 구분)
         * @param {string | null} [pipelineIds] 파이프라인 ID 목록 (콤마 구분)
         * @param {string | null} [ownerIds] 영업담당자 ID 목록 (콤마 구분)
         * @param {number} [limit] 최대 기업 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDealStagesApiV1DealStagesGet(startDate?: string | null, endDate?: string | null, companyIds?: string | null, listIds?: string | null, pipelineIds?: string | null, ownerIds?: string | null, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDealStagesApiV1DealStagesGet(startDate, endDate, companyIds, listIds, pipelineIds, ownerIds, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DealStagesApi.getDealStagesApiV1DealStagesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DealStagesApi - factory interface
 * @export
 */
export const DealStagesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DealStagesApiFp(configuration)
    return {
        /**
         * Deal Stage 히스토리 데이터 조회  기업별 Deal의 Stage 변화 히스토리를 타임라인 형식으로 반환: - Company → Leads → Deal_Contacts → Deals → Deal_Stage_History 경로로 조회 - 각 Deal의 Stage 전환 이력 및 체류 기간 포함 - pipeline_ids로 특정 파이프라인의 Deal만 필터링 가능 - owner_ids로 특정 영업담당자의 Deal만 필터링 가능
         * @summary Get Deal Stages
         * @param {DealStagesApiGetDealStagesApiV1DealStagesGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDealStagesApiV1DealStagesGet(requestParameters: DealStagesApiGetDealStagesApiV1DealStagesGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getDealStagesApiV1DealStagesGet(requestParameters.startDate, requestParameters.endDate, requestParameters.companyIds, requestParameters.listIds, requestParameters.pipelineIds, requestParameters.ownerIds, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getDealStagesApiV1DealStagesGet operation in DealStagesApi.
 * @export
 * @interface DealStagesApiGetDealStagesApiV1DealStagesGetRequest
 */
export interface DealStagesApiGetDealStagesApiV1DealStagesGetRequest {
    /**
     * 시작일 (YYYY-MM-DD)
     * @type {string}
     * @memberof DealStagesApiGetDealStagesApiV1DealStagesGet
     */
    readonly startDate?: string | null

    /**
     * 종료일 (YYYY-MM-DD)
     * @type {string}
     * @memberof DealStagesApiGetDealStagesApiV1DealStagesGet
     */
    readonly endDate?: string | null

    /**
     * 기업 ID 목록 (콤마 구분)
     * @type {string}
     * @memberof DealStagesApiGetDealStagesApiV1DealStagesGet
     */
    readonly companyIds?: string | null

    /**
     * 리스트 ID 목록 (콤마 구분)
     * @type {string}
     * @memberof DealStagesApiGetDealStagesApiV1DealStagesGet
     */
    readonly listIds?: string | null

    /**
     * 파이프라인 ID 목록 (콤마 구분)
     * @type {string}
     * @memberof DealStagesApiGetDealStagesApiV1DealStagesGet
     */
    readonly pipelineIds?: string | null

    /**
     * 영업담당자 ID 목록 (콤마 구분)
     * @type {string}
     * @memberof DealStagesApiGetDealStagesApiV1DealStagesGet
     */
    readonly ownerIds?: string | null

    /**
     * 최대 기업 수
     * @type {number}
     * @memberof DealStagesApiGetDealStagesApiV1DealStagesGet
     */
    readonly limit?: number
}

/**
 * DealStagesApi - object-oriented interface
 * @export
 * @class DealStagesApi
 * @extends {BaseAPI}
 */
export class DealStagesApi extends BaseAPI {
    /**
     * Deal Stage 히스토리 데이터 조회  기업별 Deal의 Stage 변화 히스토리를 타임라인 형식으로 반환: - Company → Leads → Deal_Contacts → Deals → Deal_Stage_History 경로로 조회 - 각 Deal의 Stage 전환 이력 및 체류 기간 포함 - pipeline_ids로 특정 파이프라인의 Deal만 필터링 가능 - owner_ids로 특정 영업담당자의 Deal만 필터링 가능
     * @summary Get Deal Stages
     * @param {DealStagesApiGetDealStagesApiV1DealStagesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DealStagesApi
     */
    public getDealStagesApiV1DealStagesGet(requestParameters: DealStagesApiGetDealStagesApiV1DealStagesGetRequest = {}, options?: RawAxiosRequestConfig) {
        return DealStagesApiFp(this.configuration).getDealStagesApiV1DealStagesGet(requestParameters.startDate, requestParameters.endDate, requestParameters.companyIds, requestParameters.listIds, requestParameters.pipelineIds, requestParameters.ownerIds, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }
}

