/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HTTPValidationError } from '../model';
// @ts-ignore
import type { HeatmapResponse } from '../model';
/**
 * HeatmapApi - axios parameter creator
 * @export
 */
export const HeatmapApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 기업 목록 검색  히트맵에 표시할 기업을 검색합니다.
         * @summary Get Companies
         * @param {string | null} [search] 기업명 검색어
         * @param {number} [limit] 최대 결과 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCompaniesApiV1HeatmapCompaniesGet: async (search?: string | null, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/heatmap/companies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 마케팅 이벤트 목록 조회  기간 내 마케팅 이벤트 목록을 반환합니다.
         * @summary Get Events
         * @param {string | null} [startDate] 시작일
         * @param {string | null} [endDate] 종료일
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEventsApiV1HeatmapEventsGet: async (startDate?: string | null, endDate?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/heatmap/events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (startDate !== undefined) {
                localVarQueryParameter['start_date'] = (startDate as any instanceof Date) ?
                    (startDate as any).toISOString().substring(0,10) :
                    startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['end_date'] = (endDate as any instanceof Date) ?
                    (endDate as any).toISOString().substring(0,10) :
                    endDate;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 히트맵 데이터 조회  기업별 신뢰 점수 시계열 데이터와 마케팅 이벤트, 참석 정보를 반환합니다.  - **start_date**: 조회 시작일 (기본: 6개월 전) - **end_date**: 조회 종료일 (기본: 오늘) - **company_ids**: 필터링할 기업 ID (쉼표 구분) - **list_ids**: 필터링할 리스트 ID (쉼표 구분) - **limit**: 최대 조회 기업 수 (기본: 100, 최대: 1000)
         * @summary Get Heatmap
         * @param {string | null} [startDate] 시작일 (기본: 6개월 전)
         * @param {string | null} [endDate] 종료일 (기본: 오늘)
         * @param {string | null} [companyIds] 쉼표로 구분된 기업 ID 목록
         * @param {string | null} [listIds] 쉼표로 구분된 리스트 ID 목록 (리스트에 속한 기업만 조회)
         * @param {number} [limit] 최대 기업 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHeatmapApiV1HeatmapGet: async (startDate?: string | null, endDate?: string | null, companyIds?: string | null, listIds?: string | null, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/heatmap`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (startDate !== undefined) {
                localVarQueryParameter['start_date'] = (startDate as any instanceof Date) ?
                    (startDate as any).toISOString().substring(0,10) :
                    startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['end_date'] = (endDate as any instanceof Date) ?
                    (endDate as any).toISOString().substring(0,10) :
                    endDate;
            }

            if (companyIds !== undefined) {
                localVarQueryParameter['company_ids'] = companyIds;
            }

            if (listIds !== undefined) {
                localVarQueryParameter['list_ids'] = listIds;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * HubSpot 리스트 목록 조회  필터링에 사용할 수 있는 리스트 목록을 반환합니다.
         * @summary Get Lists
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListsApiV1HeatmapListsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/heatmap/lists`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HeatmapApi - functional programming interface
 * @export
 */
export const HeatmapApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HeatmapApiAxiosParamCreator(configuration)
    return {
        /**
         * 기업 목록 검색  히트맵에 표시할 기업을 검색합니다.
         * @summary Get Companies
         * @param {string | null} [search] 기업명 검색어
         * @param {number} [limit] 최대 결과 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCompaniesApiV1HeatmapCompaniesGet(search?: string | null, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCompaniesApiV1HeatmapCompaniesGet(search, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HeatmapApi.getCompaniesApiV1HeatmapCompaniesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 마케팅 이벤트 목록 조회  기간 내 마케팅 이벤트 목록을 반환합니다.
         * @summary Get Events
         * @param {string | null} [startDate] 시작일
         * @param {string | null} [endDate] 종료일
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEventsApiV1HeatmapEventsGet(startDate?: string | null, endDate?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEventsApiV1HeatmapEventsGet(startDate, endDate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HeatmapApi.getEventsApiV1HeatmapEventsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 히트맵 데이터 조회  기업별 신뢰 점수 시계열 데이터와 마케팅 이벤트, 참석 정보를 반환합니다.  - **start_date**: 조회 시작일 (기본: 6개월 전) - **end_date**: 조회 종료일 (기본: 오늘) - **company_ids**: 필터링할 기업 ID (쉼표 구분) - **list_ids**: 필터링할 리스트 ID (쉼표 구분) - **limit**: 최대 조회 기업 수 (기본: 100, 최대: 1000)
         * @summary Get Heatmap
         * @param {string | null} [startDate] 시작일 (기본: 6개월 전)
         * @param {string | null} [endDate] 종료일 (기본: 오늘)
         * @param {string | null} [companyIds] 쉼표로 구분된 기업 ID 목록
         * @param {string | null} [listIds] 쉼표로 구분된 리스트 ID 목록 (리스트에 속한 기업만 조회)
         * @param {number} [limit] 최대 기업 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHeatmapApiV1HeatmapGet(startDate?: string | null, endDate?: string | null, companyIds?: string | null, listIds?: string | null, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HeatmapResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHeatmapApiV1HeatmapGet(startDate, endDate, companyIds, listIds, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HeatmapApi.getHeatmapApiV1HeatmapGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * HubSpot 리스트 목록 조회  필터링에 사용할 수 있는 리스트 목록을 반환합니다.
         * @summary Get Lists
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getListsApiV1HeatmapListsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getListsApiV1HeatmapListsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HeatmapApi.getListsApiV1HeatmapListsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HeatmapApi - factory interface
 * @export
 */
export const HeatmapApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HeatmapApiFp(configuration)
    return {
        /**
         * 기업 목록 검색  히트맵에 표시할 기업을 검색합니다.
         * @summary Get Companies
         * @param {HeatmapApiGetCompaniesApiV1HeatmapCompaniesGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCompaniesApiV1HeatmapCompaniesGet(requestParameters: HeatmapApiGetCompaniesApiV1HeatmapCompaniesGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getCompaniesApiV1HeatmapCompaniesGet(requestParameters.search, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 마케팅 이벤트 목록 조회  기간 내 마케팅 이벤트 목록을 반환합니다.
         * @summary Get Events
         * @param {HeatmapApiGetEventsApiV1HeatmapEventsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEventsApiV1HeatmapEventsGet(requestParameters: HeatmapApiGetEventsApiV1HeatmapEventsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getEventsApiV1HeatmapEventsGet(requestParameters.startDate, requestParameters.endDate, options).then((request) => request(axios, basePath));
        },
        /**
         * 히트맵 데이터 조회  기업별 신뢰 점수 시계열 데이터와 마케팅 이벤트, 참석 정보를 반환합니다.  - **start_date**: 조회 시작일 (기본: 6개월 전) - **end_date**: 조회 종료일 (기본: 오늘) - **company_ids**: 필터링할 기업 ID (쉼표 구분) - **list_ids**: 필터링할 리스트 ID (쉼표 구분) - **limit**: 최대 조회 기업 수 (기본: 100, 최대: 1000)
         * @summary Get Heatmap
         * @param {HeatmapApiGetHeatmapApiV1HeatmapGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHeatmapApiV1HeatmapGet(requestParameters: HeatmapApiGetHeatmapApiV1HeatmapGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<HeatmapResponse> {
            return localVarFp.getHeatmapApiV1HeatmapGet(requestParameters.startDate, requestParameters.endDate, requestParameters.companyIds, requestParameters.listIds, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * HubSpot 리스트 목록 조회  필터링에 사용할 수 있는 리스트 목록을 반환합니다.
         * @summary Get Lists
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListsApiV1HeatmapListsGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getListsApiV1HeatmapListsGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getCompaniesApiV1HeatmapCompaniesGet operation in HeatmapApi.
 * @export
 * @interface HeatmapApiGetCompaniesApiV1HeatmapCompaniesGetRequest
 */
export interface HeatmapApiGetCompaniesApiV1HeatmapCompaniesGetRequest {
    /**
     * 기업명 검색어
     * @type {string}
     * @memberof HeatmapApiGetCompaniesApiV1HeatmapCompaniesGet
     */
    readonly search?: string | null

    /**
     * 최대 결과 수
     * @type {number}
     * @memberof HeatmapApiGetCompaniesApiV1HeatmapCompaniesGet
     */
    readonly limit?: number
}

/**
 * Request parameters for getEventsApiV1HeatmapEventsGet operation in HeatmapApi.
 * @export
 * @interface HeatmapApiGetEventsApiV1HeatmapEventsGetRequest
 */
export interface HeatmapApiGetEventsApiV1HeatmapEventsGetRequest {
    /**
     * 시작일
     * @type {string}
     * @memberof HeatmapApiGetEventsApiV1HeatmapEventsGet
     */
    readonly startDate?: string | null

    /**
     * 종료일
     * @type {string}
     * @memberof HeatmapApiGetEventsApiV1HeatmapEventsGet
     */
    readonly endDate?: string | null
}

/**
 * Request parameters for getHeatmapApiV1HeatmapGet operation in HeatmapApi.
 * @export
 * @interface HeatmapApiGetHeatmapApiV1HeatmapGetRequest
 */
export interface HeatmapApiGetHeatmapApiV1HeatmapGetRequest {
    /**
     * 시작일 (기본: 6개월 전)
     * @type {string}
     * @memberof HeatmapApiGetHeatmapApiV1HeatmapGet
     */
    readonly startDate?: string | null

    /**
     * 종료일 (기본: 오늘)
     * @type {string}
     * @memberof HeatmapApiGetHeatmapApiV1HeatmapGet
     */
    readonly endDate?: string | null

    /**
     * 쉼표로 구분된 기업 ID 목록
     * @type {string}
     * @memberof HeatmapApiGetHeatmapApiV1HeatmapGet
     */
    readonly companyIds?: string | null

    /**
     * 쉼표로 구분된 리스트 ID 목록 (리스트에 속한 기업만 조회)
     * @type {string}
     * @memberof HeatmapApiGetHeatmapApiV1HeatmapGet
     */
    readonly listIds?: string | null

    /**
     * 최대 기업 수
     * @type {number}
     * @memberof HeatmapApiGetHeatmapApiV1HeatmapGet
     */
    readonly limit?: number
}

/**
 * HeatmapApi - object-oriented interface
 * @export
 * @class HeatmapApi
 * @extends {BaseAPI}
 */
export class HeatmapApi extends BaseAPI {
    /**
     * 기업 목록 검색  히트맵에 표시할 기업을 검색합니다.
     * @summary Get Companies
     * @param {HeatmapApiGetCompaniesApiV1HeatmapCompaniesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HeatmapApi
     */
    public getCompaniesApiV1HeatmapCompaniesGet(requestParameters: HeatmapApiGetCompaniesApiV1HeatmapCompaniesGetRequest = {}, options?: RawAxiosRequestConfig) {
        return HeatmapApiFp(this.configuration).getCompaniesApiV1HeatmapCompaniesGet(requestParameters.search, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 마케팅 이벤트 목록 조회  기간 내 마케팅 이벤트 목록을 반환합니다.
     * @summary Get Events
     * @param {HeatmapApiGetEventsApiV1HeatmapEventsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HeatmapApi
     */
    public getEventsApiV1HeatmapEventsGet(requestParameters: HeatmapApiGetEventsApiV1HeatmapEventsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return HeatmapApiFp(this.configuration).getEventsApiV1HeatmapEventsGet(requestParameters.startDate, requestParameters.endDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 히트맵 데이터 조회  기업별 신뢰 점수 시계열 데이터와 마케팅 이벤트, 참석 정보를 반환합니다.  - **start_date**: 조회 시작일 (기본: 6개월 전) - **end_date**: 조회 종료일 (기본: 오늘) - **company_ids**: 필터링할 기업 ID (쉼표 구분) - **list_ids**: 필터링할 리스트 ID (쉼표 구분) - **limit**: 최대 조회 기업 수 (기본: 100, 최대: 1000)
     * @summary Get Heatmap
     * @param {HeatmapApiGetHeatmapApiV1HeatmapGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HeatmapApi
     */
    public getHeatmapApiV1HeatmapGet(requestParameters: HeatmapApiGetHeatmapApiV1HeatmapGetRequest = {}, options?: RawAxiosRequestConfig) {
        return HeatmapApiFp(this.configuration).getHeatmapApiV1HeatmapGet(requestParameters.startDate, requestParameters.endDate, requestParameters.companyIds, requestParameters.listIds, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * HubSpot 리스트 목록 조회  필터링에 사용할 수 있는 리스트 목록을 반환합니다.
     * @summary Get Lists
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HeatmapApi
     */
    public getListsApiV1HeatmapListsGet(options?: RawAxiosRequestConfig) {
        return HeatmapApiFp(this.configuration).getListsApiV1HeatmapListsGet(options).then((request) => request(this.axios, this.basePath));
    }
}

