/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HTTPValidationError } from '../model';
/**
 * TimelineApi - axios parameter creator
 * @export
 */
export const TimelineApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 타임라인 이벤트 데이터 조회  기업별 모든 이벤트를 타임라인 형식으로 반환: - Sales Activities: calls, meetings, notes, emails - Marketing Events: event attendance - Engagement Events: page_view, form_submit, email_click, email_open
         * @summary Get Timeline Data
         * @param {string | null} [startDate] 시작일 (YYYY-MM-DD)
         * @param {string | null} [endDate] 종료일 (YYYY-MM-DD)
         * @param {string | null} [companyIds] 기업 ID 목록 (콤마 구분)
         * @param {string | null} [listIds] 리스트 ID 목록 (콤마 구분)
         * @param {string | null} [ownerIds] 담당자 ID 목록 (콤마 구분)
         * @param {string | null} [productUsages] 제품 사용 목록 (콤마 구분)
         * @param {number} [limit] 최대 기업 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTimelineDataApiV1TimelineGet: async (startDate?: string | null, endDate?: string | null, companyIds?: string | null, listIds?: string | null, ownerIds?: string | null, productUsages?: string | null, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/timeline`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (startDate !== undefined) {
                localVarQueryParameter['start_date'] = startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['end_date'] = endDate;
            }

            if (companyIds !== undefined) {
                localVarQueryParameter['company_ids'] = companyIds;
            }

            if (listIds !== undefined) {
                localVarQueryParameter['list_ids'] = listIds;
            }

            if (ownerIds !== undefined) {
                localVarQueryParameter['owner_ids'] = ownerIds;
            }

            if (productUsages !== undefined) {
                localVarQueryParameter['product_usages'] = productUsages;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TimelineApi - functional programming interface
 * @export
 */
export const TimelineApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TimelineApiAxiosParamCreator(configuration)
    return {
        /**
         * 타임라인 이벤트 데이터 조회  기업별 모든 이벤트를 타임라인 형식으로 반환: - Sales Activities: calls, meetings, notes, emails - Marketing Events: event attendance - Engagement Events: page_view, form_submit, email_click, email_open
         * @summary Get Timeline Data
         * @param {string | null} [startDate] 시작일 (YYYY-MM-DD)
         * @param {string | null} [endDate] 종료일 (YYYY-MM-DD)
         * @param {string | null} [companyIds] 기업 ID 목록 (콤마 구분)
         * @param {string | null} [listIds] 리스트 ID 목록 (콤마 구분)
         * @param {string | null} [ownerIds] 담당자 ID 목록 (콤마 구분)
         * @param {string | null} [productUsages] 제품 사용 목록 (콤마 구분)
         * @param {number} [limit] 최대 기업 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTimelineDataApiV1TimelineGet(startDate?: string | null, endDate?: string | null, companyIds?: string | null, listIds?: string | null, ownerIds?: string | null, productUsages?: string | null, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTimelineDataApiV1TimelineGet(startDate, endDate, companyIds, listIds, ownerIds, productUsages, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TimelineApi.getTimelineDataApiV1TimelineGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TimelineApi - factory interface
 * @export
 */
export const TimelineApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TimelineApiFp(configuration)
    return {
        /**
         * 타임라인 이벤트 데이터 조회  기업별 모든 이벤트를 타임라인 형식으로 반환: - Sales Activities: calls, meetings, notes, emails - Marketing Events: event attendance - Engagement Events: page_view, form_submit, email_click, email_open
         * @summary Get Timeline Data
         * @param {TimelineApiGetTimelineDataApiV1TimelineGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTimelineDataApiV1TimelineGet(requestParameters: TimelineApiGetTimelineDataApiV1TimelineGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getTimelineDataApiV1TimelineGet(requestParameters.startDate, requestParameters.endDate, requestParameters.companyIds, requestParameters.listIds, requestParameters.ownerIds, requestParameters.productUsages, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getTimelineDataApiV1TimelineGet operation in TimelineApi.
 * @export
 * @interface TimelineApiGetTimelineDataApiV1TimelineGetRequest
 */
export interface TimelineApiGetTimelineDataApiV1TimelineGetRequest {
    /**
     * 시작일 (YYYY-MM-DD)
     * @type {string}
     * @memberof TimelineApiGetTimelineDataApiV1TimelineGet
     */
    readonly startDate?: string | null

    /**
     * 종료일 (YYYY-MM-DD)
     * @type {string}
     * @memberof TimelineApiGetTimelineDataApiV1TimelineGet
     */
    readonly endDate?: string | null

    /**
     * 기업 ID 목록 (콤마 구분)
     * @type {string}
     * @memberof TimelineApiGetTimelineDataApiV1TimelineGet
     */
    readonly companyIds?: string | null

    /**
     * 리스트 ID 목록 (콤마 구분)
     * @type {string}
     * @memberof TimelineApiGetTimelineDataApiV1TimelineGet
     */
    readonly listIds?: string | null

    /**
     * 담당자 ID 목록 (콤마 구분)
     * @type {string}
     * @memberof TimelineApiGetTimelineDataApiV1TimelineGet
     */
    readonly ownerIds?: string | null

    /**
     * 제품 사용 목록 (콤마 구분)
     * @type {string}
     * @memberof TimelineApiGetTimelineDataApiV1TimelineGet
     */
    readonly productUsages?: string | null

    /**
     * 최대 기업 수
     * @type {number}
     * @memberof TimelineApiGetTimelineDataApiV1TimelineGet
     */
    readonly limit?: number
}

/**
 * TimelineApi - object-oriented interface
 * @export
 * @class TimelineApi
 * @extends {BaseAPI}
 */
export class TimelineApi extends BaseAPI {
    /**
     * 타임라인 이벤트 데이터 조회  기업별 모든 이벤트를 타임라인 형식으로 반환: - Sales Activities: calls, meetings, notes, emails - Marketing Events: event attendance - Engagement Events: page_view, form_submit, email_click, email_open
     * @summary Get Timeline Data
     * @param {TimelineApiGetTimelineDataApiV1TimelineGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TimelineApi
     */
    public getTimelineDataApiV1TimelineGet(requestParameters: TimelineApiGetTimelineDataApiV1TimelineGetRequest = {}, options?: RawAxiosRequestConfig) {
        return TimelineApiFp(this.configuration).getTimelineDataApiV1TimelineGet(requestParameters.startDate, requestParameters.endDate, requestParameters.companyIds, requestParameters.listIds, requestParameters.ownerIds, requestParameters.productUsages, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }
}

