/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Category } from '../model';
// @ts-ignore
import type { HTTPValidationError } from '../model';
// @ts-ignore
import type { TimePeriod } from '../model';
// @ts-ignore
import type { TrustIndexCardResponse } from '../model';
/**
 * TrustIndexCardApi - axios parameter creator
 * @export
 */
export const TrustIndexCardApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 신뢰지수 변동 카드 조회  전체 집합을 기준으로 계산하며, 테이블 필터를 따로 적용하지 않습니다.  - **period**: 기간 필터 (WEEK | MONTH | HALF_YEAR | YEAR)     - WEEK: 1주 전 데이터와 비교     - MONTH: 1개월 전 데이터와 비교     - HALF_YEAR: 6개월 전 데이터와 비교     - YEAR: 1년 전 데이터와 비교 - **category**: 카테고리 필터 (선택적)     - recruit: 채용     - performance: 성과     - public: 공공     - 미지정 시 전체 카테고리 대상  Returns:     TrustIndexCardResponse:         - trustUp: 신뢰지수 상승 기업 목록 (변화량 내림차순)         - trustDown: 신뢰지수 하락 기업 목록 (변화량 내림차순)
         * @summary Get Trust Index Card
         * @param {TimePeriod} [period] 기간 필터
         * @param {Category | null} [category] 카테고리 필터 (선택적)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTrustIndexCardApiV1DashboardTrustIndexGet: async (period?: TimePeriod, category?: Category | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/dashboard/trust-index`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (period !== undefined) {
                localVarQueryParameter['period'] = period;
            }

            if (category !== undefined) {
                localVarQueryParameter['category'] = category;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TrustIndexCardApi - functional programming interface
 * @export
 */
export const TrustIndexCardApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TrustIndexCardApiAxiosParamCreator(configuration)
    return {
        /**
         * 신뢰지수 변동 카드 조회  전체 집합을 기준으로 계산하며, 테이블 필터를 따로 적용하지 않습니다.  - **period**: 기간 필터 (WEEK | MONTH | HALF_YEAR | YEAR)     - WEEK: 1주 전 데이터와 비교     - MONTH: 1개월 전 데이터와 비교     - HALF_YEAR: 6개월 전 데이터와 비교     - YEAR: 1년 전 데이터와 비교 - **category**: 카테고리 필터 (선택적)     - recruit: 채용     - performance: 성과     - public: 공공     - 미지정 시 전체 카테고리 대상  Returns:     TrustIndexCardResponse:         - trustUp: 신뢰지수 상승 기업 목록 (변화량 내림차순)         - trustDown: 신뢰지수 하락 기업 목록 (변화량 내림차순)
         * @summary Get Trust Index Card
         * @param {TimePeriod} [period] 기간 필터
         * @param {Category | null} [category] 카테고리 필터 (선택적)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTrustIndexCardApiV1DashboardTrustIndexGet(period?: TimePeriod, category?: Category | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TrustIndexCardResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTrustIndexCardApiV1DashboardTrustIndexGet(period, category, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TrustIndexCardApi.getTrustIndexCardApiV1DashboardTrustIndexGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TrustIndexCardApi - factory interface
 * @export
 */
export const TrustIndexCardApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TrustIndexCardApiFp(configuration)
    return {
        /**
         * 신뢰지수 변동 카드 조회  전체 집합을 기준으로 계산하며, 테이블 필터를 따로 적용하지 않습니다.  - **period**: 기간 필터 (WEEK | MONTH | HALF_YEAR | YEAR)     - WEEK: 1주 전 데이터와 비교     - MONTH: 1개월 전 데이터와 비교     - HALF_YEAR: 6개월 전 데이터와 비교     - YEAR: 1년 전 데이터와 비교 - **category**: 카테고리 필터 (선택적)     - recruit: 채용     - performance: 성과     - public: 공공     - 미지정 시 전체 카테고리 대상  Returns:     TrustIndexCardResponse:         - trustUp: 신뢰지수 상승 기업 목록 (변화량 내림차순)         - trustDown: 신뢰지수 하락 기업 목록 (변화량 내림차순)
         * @summary Get Trust Index Card
         * @param {TrustIndexCardApiGetTrustIndexCardApiV1DashboardTrustIndexGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTrustIndexCardApiV1DashboardTrustIndexGet(requestParameters: TrustIndexCardApiGetTrustIndexCardApiV1DashboardTrustIndexGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<TrustIndexCardResponse> {
            return localVarFp.getTrustIndexCardApiV1DashboardTrustIndexGet(requestParameters.period, requestParameters.category, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getTrustIndexCardApiV1DashboardTrustIndexGet operation in TrustIndexCardApi.
 * @export
 * @interface TrustIndexCardApiGetTrustIndexCardApiV1DashboardTrustIndexGetRequest
 */
export interface TrustIndexCardApiGetTrustIndexCardApiV1DashboardTrustIndexGetRequest {
    /**
     * 기간 필터
     * @type {TimePeriod}
     * @memberof TrustIndexCardApiGetTrustIndexCardApiV1DashboardTrustIndexGet
     */
    readonly period?: TimePeriod

    /**
     * 카테고리 필터 (선택적)
     * @type {Category}
     * @memberof TrustIndexCardApiGetTrustIndexCardApiV1DashboardTrustIndexGet
     */
    readonly category?: Category | null
}

/**
 * TrustIndexCardApi - object-oriented interface
 * @export
 * @class TrustIndexCardApi
 * @extends {BaseAPI}
 */
export class TrustIndexCardApi extends BaseAPI {
    /**
     * 신뢰지수 변동 카드 조회  전체 집합을 기준으로 계산하며, 테이블 필터를 따로 적용하지 않습니다.  - **period**: 기간 필터 (WEEK | MONTH | HALF_YEAR | YEAR)     - WEEK: 1주 전 데이터와 비교     - MONTH: 1개월 전 데이터와 비교     - HALF_YEAR: 6개월 전 데이터와 비교     - YEAR: 1년 전 데이터와 비교 - **category**: 카테고리 필터 (선택적)     - recruit: 채용     - performance: 성과     - public: 공공     - 미지정 시 전체 카테고리 대상  Returns:     TrustIndexCardResponse:         - trustUp: 신뢰지수 상승 기업 목록 (변화량 내림차순)         - trustDown: 신뢰지수 하락 기업 목록 (변화량 내림차순)
     * @summary Get Trust Index Card
     * @param {TrustIndexCardApiGetTrustIndexCardApiV1DashboardTrustIndexGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrustIndexCardApi
     */
    public getTrustIndexCardApiV1DashboardTrustIndexGet(requestParameters: TrustIndexCardApiGetTrustIndexCardApiV1DashboardTrustIndexGetRequest = {}, options?: RawAxiosRequestConfig) {
        return TrustIndexCardApiFp(this.configuration).getTrustIndexCardApiV1DashboardTrustIndexGet(requestParameters.period, requestParameters.category, options).then((request) => request(this.axios, this.basePath));
    }
}

