/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HTTPValidationError } from '../model';
// @ts-ignore
import type { TimePeriod } from '../model';
// @ts-ignore
import type { TrustChangeDetailResponse } from '../model';
/**
 * TrustChangeDetailApi - axios parameter creator
 * @export
 */
export const TrustChangeDetailApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 신뢰지수 변동 상세 조회  신뢰지수 변동 기업 리스트에서 특정 기업 카드를 클릭했을 때 표시되는 상세 모달 데이터입니다.  - **companyId**: 조회할 기업 ID (필수) - **period**: 조회 기간 (WEEK | MONTH | HALF_YEAR | YEAR)     - 해당 기간 내의 콘텐츠 소비 및 MBM 참석 이력 제공  Returns:     TrustChangeDetailResponse:         - companyId: 기업 ID         - companyName: 기업명         - manager: 담당 영업사원         - category: 카테고리 (채용/공공/병원/성과)         - companySize: 기업 규모 (T0/T1/T3/T5/T9/T10)         - trustIndex: 현재 신뢰지수         - trustLevel: 신뢰레벨 (P1/P2/P3)         - changeAmount: 신뢰지수 변화량 (절댓값)         - changeDirection: 변화 방향 (up/down/none)         - engagementScores: Engagement Score 목록 (이벤트 기반 활동)         - fitScores: Fit Score 목록 (속성 기반 점수)
         * @summary Get Trust Change Detail
         * @param {number} companyId 조회할 기업 ID
         * @param {TimePeriod} [period] 조회 기간
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTrustChangeDetailApiV1DashboardTrustChangeDetailGet: async (companyId: number, period?: TimePeriod, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyId' is not null or undefined
            assertParamExists('getTrustChangeDetailApiV1DashboardTrustChangeDetailGet', 'companyId', companyId)
            const localVarPath = `/api/v1/dashboard/trust-change-detail`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (companyId !== undefined) {
                localVarQueryParameter['companyId'] = companyId;
            }

            if (period !== undefined) {
                localVarQueryParameter['period'] = period;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TrustChangeDetailApi - functional programming interface
 * @export
 */
export const TrustChangeDetailApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TrustChangeDetailApiAxiosParamCreator(configuration)
    return {
        /**
         * 신뢰지수 변동 상세 조회  신뢰지수 변동 기업 리스트에서 특정 기업 카드를 클릭했을 때 표시되는 상세 모달 데이터입니다.  - **companyId**: 조회할 기업 ID (필수) - **period**: 조회 기간 (WEEK | MONTH | HALF_YEAR | YEAR)     - 해당 기간 내의 콘텐츠 소비 및 MBM 참석 이력 제공  Returns:     TrustChangeDetailResponse:         - companyId: 기업 ID         - companyName: 기업명         - manager: 담당 영업사원         - category: 카테고리 (채용/공공/병원/성과)         - companySize: 기업 규모 (T0/T1/T3/T5/T9/T10)         - trustIndex: 현재 신뢰지수         - trustLevel: 신뢰레벨 (P1/P2/P3)         - changeAmount: 신뢰지수 변화량 (절댓값)         - changeDirection: 변화 방향 (up/down/none)         - engagementScores: Engagement Score 목록 (이벤트 기반 활동)         - fitScores: Fit Score 목록 (속성 기반 점수)
         * @summary Get Trust Change Detail
         * @param {number} companyId 조회할 기업 ID
         * @param {TimePeriod} [period] 조회 기간
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTrustChangeDetailApiV1DashboardTrustChangeDetailGet(companyId: number, period?: TimePeriod, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TrustChangeDetailResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTrustChangeDetailApiV1DashboardTrustChangeDetailGet(companyId, period, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TrustChangeDetailApi.getTrustChangeDetailApiV1DashboardTrustChangeDetailGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TrustChangeDetailApi - factory interface
 * @export
 */
export const TrustChangeDetailApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TrustChangeDetailApiFp(configuration)
    return {
        /**
         * 신뢰지수 변동 상세 조회  신뢰지수 변동 기업 리스트에서 특정 기업 카드를 클릭했을 때 표시되는 상세 모달 데이터입니다.  - **companyId**: 조회할 기업 ID (필수) - **period**: 조회 기간 (WEEK | MONTH | HALF_YEAR | YEAR)     - 해당 기간 내의 콘텐츠 소비 및 MBM 참석 이력 제공  Returns:     TrustChangeDetailResponse:         - companyId: 기업 ID         - companyName: 기업명         - manager: 담당 영업사원         - category: 카테고리 (채용/공공/병원/성과)         - companySize: 기업 규모 (T0/T1/T3/T5/T9/T10)         - trustIndex: 현재 신뢰지수         - trustLevel: 신뢰레벨 (P1/P2/P3)         - changeAmount: 신뢰지수 변화량 (절댓값)         - changeDirection: 변화 방향 (up/down/none)         - engagementScores: Engagement Score 목록 (이벤트 기반 활동)         - fitScores: Fit Score 목록 (속성 기반 점수)
         * @summary Get Trust Change Detail
         * @param {TrustChangeDetailApiGetTrustChangeDetailApiV1DashboardTrustChangeDetailGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTrustChangeDetailApiV1DashboardTrustChangeDetailGet(requestParameters: TrustChangeDetailApiGetTrustChangeDetailApiV1DashboardTrustChangeDetailGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<TrustChangeDetailResponse> {
            return localVarFp.getTrustChangeDetailApiV1DashboardTrustChangeDetailGet(requestParameters.companyId, requestParameters.period, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getTrustChangeDetailApiV1DashboardTrustChangeDetailGet operation in TrustChangeDetailApi.
 * @export
 * @interface TrustChangeDetailApiGetTrustChangeDetailApiV1DashboardTrustChangeDetailGetRequest
 */
export interface TrustChangeDetailApiGetTrustChangeDetailApiV1DashboardTrustChangeDetailGetRequest {
    /**
     * 조회할 기업 ID
     * @type {number}
     * @memberof TrustChangeDetailApiGetTrustChangeDetailApiV1DashboardTrustChangeDetailGet
     */
    readonly companyId: number

    /**
     * 조회 기간
     * @type {TimePeriod}
     * @memberof TrustChangeDetailApiGetTrustChangeDetailApiV1DashboardTrustChangeDetailGet
     */
    readonly period?: TimePeriod
}

/**
 * TrustChangeDetailApi - object-oriented interface
 * @export
 * @class TrustChangeDetailApi
 * @extends {BaseAPI}
 */
export class TrustChangeDetailApi extends BaseAPI {
    /**
     * 신뢰지수 변동 상세 조회  신뢰지수 변동 기업 리스트에서 특정 기업 카드를 클릭했을 때 표시되는 상세 모달 데이터입니다.  - **companyId**: 조회할 기업 ID (필수) - **period**: 조회 기간 (WEEK | MONTH | HALF_YEAR | YEAR)     - 해당 기간 내의 콘텐츠 소비 및 MBM 참석 이력 제공  Returns:     TrustChangeDetailResponse:         - companyId: 기업 ID         - companyName: 기업명         - manager: 담당 영업사원         - category: 카테고리 (채용/공공/병원/성과)         - companySize: 기업 규모 (T0/T1/T3/T5/T9/T10)         - trustIndex: 현재 신뢰지수         - trustLevel: 신뢰레벨 (P1/P2/P3)         - changeAmount: 신뢰지수 변화량 (절댓값)         - changeDirection: 변화 방향 (up/down/none)         - engagementScores: Engagement Score 목록 (이벤트 기반 활동)         - fitScores: Fit Score 목록 (속성 기반 점수)
     * @summary Get Trust Change Detail
     * @param {TrustChangeDetailApiGetTrustChangeDetailApiV1DashboardTrustChangeDetailGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrustChangeDetailApi
     */
    public getTrustChangeDetailApiV1DashboardTrustChangeDetailGet(requestParameters: TrustChangeDetailApiGetTrustChangeDetailApiV1DashboardTrustChangeDetailGetRequest, options?: RawAxiosRequestConfig) {
        return TrustChangeDetailApiFp(this.configuration).getTrustChangeDetailApiV1DashboardTrustChangeDetailGet(requestParameters.companyId, requestParameters.period, options).then((request) => request(this.axios, this.basePath));
    }
}

