/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HTTPValidationError } from '../model';
// @ts-ignore
import type { TrustChangeDetailRequest } from '../model';
// @ts-ignore
import type { TrustChangeDetailResponse } from '../model';
/**
 * TrustChangeDetailApi - axios parameter creator
 * @export
 */
export const TrustChangeDetailApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 신뢰지수 변동 상세 조회  신뢰지수 변동 기업 리스트에서 특정 기업 카드를 클릭했을 때 표시되는 상세 모달 데이터입니다.  - **companyId**: 조회할 기업 ID (필수) - **dateRange**: 조회 기간 (startDate ~ endDate, YYYY-MM-DD 형식)     - 해당 기간 내의 콘텐츠 소비 및 MBM 참석 이력 제공  Returns:     TrustChangeDetailResponse:         - changeAmount: 신뢰지수 변화량         - engagementItems: Engagement 목록 (이벤트 기반 활동)
         * @summary Get Trust Change Detail
         * @param {TrustChangeDetailRequest} trustChangeDetailRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTrustChangeDetailApiV1DashboardTrustChangeDetailPost: async (trustChangeDetailRequest: TrustChangeDetailRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'trustChangeDetailRequest' is not null or undefined
            assertParamExists('getTrustChangeDetailApiV1DashboardTrustChangeDetailPost', 'trustChangeDetailRequest', trustChangeDetailRequest)
            const localVarPath = `/api/v1/dashboard/trust-change-detail`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(trustChangeDetailRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TrustChangeDetailApi - functional programming interface
 * @export
 */
export const TrustChangeDetailApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TrustChangeDetailApiAxiosParamCreator(configuration)
    return {
        /**
         * 신뢰지수 변동 상세 조회  신뢰지수 변동 기업 리스트에서 특정 기업 카드를 클릭했을 때 표시되는 상세 모달 데이터입니다.  - **companyId**: 조회할 기업 ID (필수) - **dateRange**: 조회 기간 (startDate ~ endDate, YYYY-MM-DD 형식)     - 해당 기간 내의 콘텐츠 소비 및 MBM 참석 이력 제공  Returns:     TrustChangeDetailResponse:         - changeAmount: 신뢰지수 변화량         - engagementItems: Engagement 목록 (이벤트 기반 활동)
         * @summary Get Trust Change Detail
         * @param {TrustChangeDetailRequest} trustChangeDetailRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTrustChangeDetailApiV1DashboardTrustChangeDetailPost(trustChangeDetailRequest: TrustChangeDetailRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TrustChangeDetailResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTrustChangeDetailApiV1DashboardTrustChangeDetailPost(trustChangeDetailRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TrustChangeDetailApi.getTrustChangeDetailApiV1DashboardTrustChangeDetailPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TrustChangeDetailApi - factory interface
 * @export
 */
export const TrustChangeDetailApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TrustChangeDetailApiFp(configuration)
    return {
        /**
         * 신뢰지수 변동 상세 조회  신뢰지수 변동 기업 리스트에서 특정 기업 카드를 클릭했을 때 표시되는 상세 모달 데이터입니다.  - **companyId**: 조회할 기업 ID (필수) - **dateRange**: 조회 기간 (startDate ~ endDate, YYYY-MM-DD 형식)     - 해당 기간 내의 콘텐츠 소비 및 MBM 참석 이력 제공  Returns:     TrustChangeDetailResponse:         - changeAmount: 신뢰지수 변화량         - engagementItems: Engagement 목록 (이벤트 기반 활동)
         * @summary Get Trust Change Detail
         * @param {TrustChangeDetailApiGetTrustChangeDetailApiV1DashboardTrustChangeDetailPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTrustChangeDetailApiV1DashboardTrustChangeDetailPost(requestParameters: TrustChangeDetailApiGetTrustChangeDetailApiV1DashboardTrustChangeDetailPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<TrustChangeDetailResponse> {
            return localVarFp.getTrustChangeDetailApiV1DashboardTrustChangeDetailPost(requestParameters.trustChangeDetailRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getTrustChangeDetailApiV1DashboardTrustChangeDetailPost operation in TrustChangeDetailApi.
 * @export
 * @interface TrustChangeDetailApiGetTrustChangeDetailApiV1DashboardTrustChangeDetailPostRequest
 */
export interface TrustChangeDetailApiGetTrustChangeDetailApiV1DashboardTrustChangeDetailPostRequest {
    /**
     * 
     * @type {TrustChangeDetailRequest}
     * @memberof TrustChangeDetailApiGetTrustChangeDetailApiV1DashboardTrustChangeDetailPost
     */
    readonly trustChangeDetailRequest: TrustChangeDetailRequest
}

/**
 * TrustChangeDetailApi - object-oriented interface
 * @export
 * @class TrustChangeDetailApi
 * @extends {BaseAPI}
 */
export class TrustChangeDetailApi extends BaseAPI {
    /**
     * 신뢰지수 변동 상세 조회  신뢰지수 변동 기업 리스트에서 특정 기업 카드를 클릭했을 때 표시되는 상세 모달 데이터입니다.  - **companyId**: 조회할 기업 ID (필수) - **dateRange**: 조회 기간 (startDate ~ endDate, YYYY-MM-DD 형식)     - 해당 기간 내의 콘텐츠 소비 및 MBM 참석 이력 제공  Returns:     TrustChangeDetailResponse:         - changeAmount: 신뢰지수 변화량         - engagementItems: Engagement 목록 (이벤트 기반 활동)
     * @summary Get Trust Change Detail
     * @param {TrustChangeDetailApiGetTrustChangeDetailApiV1DashboardTrustChangeDetailPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TrustChangeDetailApi
     */
    public getTrustChangeDetailApiV1DashboardTrustChangeDetailPost(requestParameters: TrustChangeDetailApiGetTrustChangeDetailApiV1DashboardTrustChangeDetailPostRequest, options?: RawAxiosRequestConfig) {
        return TrustChangeDetailApiFp(this.configuration).getTrustChangeDetailApiV1DashboardTrustChangeDetailPost(requestParameters.trustChangeDetailRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

