/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HTTPValidationError } from '../model';
// @ts-ignore
import type { WeeklySnapshotResponse } from '../model';
/**
 * WeeklySnapshotsApi - axios parameter creator
 * @export
 */
export const WeeklySnapshotsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 영업담당자 목록 조회 (활성 담당자만)
         * @summary Get Owners
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOwnersApiV1WeeklySnapshotsOwnersGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/weekly-snapshots/owners`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 스냅샷 데이터가 있는 기업 목록 검색
         * @summary Get Snapshot Companies
         * @param {string | null} [search] 기업명 검색어
         * @param {number} [limit] 최대 결과 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSnapshotCompaniesApiV1WeeklySnapshotsCompaniesGet: async (search?: string | null, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/weekly-snapshots/companies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 주간 스냅샷 통계 정보
         * @summary Get Snapshot Stats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSnapshotStatsApiV1WeeklySnapshotsStatsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/weekly-snapshots/stats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 주간 스냅샷 히트맵 데이터 조회  기업별 주간 스냅샷 점수 데이터를 반환합니다.  - **start_date**: 조회 시작일 (기본: 3개월 전) - **end_date**: 조회 종료일 (기본: 오늘) - **company_ids**: 필터링할 기업 ID (쉼표 구분) - **list_ids**: 필터링할 리스트 ID (쉼표 구분) - **limit**: 최대 조회 기업 수 (기본: 100, 최대: 1000)  Returns:     companies: 기업 목록     weeks: 주차 목록     scores: 기업별 주간 점수 (신규/기존 고객별 마케팅 점수, 세일즈 적합도 점수)
         * @summary Get Weekly Snapshots
         * @param {string | null} [startDate] 시작일 (기본: 3개월 전)
         * @param {string | null} [endDate] 종료일 (기본: 오늘)
         * @param {string | null} [companyIds] 쉼표로 구분된 기업 ID 목록
         * @param {string | null} [listIds] 쉼표로 구분된 리스트 ID 목록 (리스트에 속한 기업만 조회)
         * @param {string | null} [ownerIds] 쉼표로 구분된 영업담당자 ID 목록
         * @param {string | null} [productUsages] 쉼표로 구분된 제품사용 목록 (예: ATS,역량검사,온보딩)
         * @param {number} [limit] 최대 기업 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWeeklySnapshotsApiV1WeeklySnapshotsGet: async (startDate?: string | null, endDate?: string | null, companyIds?: string | null, listIds?: string | null, ownerIds?: string | null, productUsages?: string | null, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/weekly-snapshots`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (startDate !== undefined) {
                localVarQueryParameter['start_date'] = (startDate as any instanceof Date) ?
                    (startDate as any).toISOString().substring(0,10) :
                    startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['end_date'] = (endDate as any instanceof Date) ?
                    (endDate as any).toISOString().substring(0,10) :
                    endDate;
            }

            if (companyIds !== undefined) {
                localVarQueryParameter['company_ids'] = companyIds;
            }

            if (listIds !== undefined) {
                localVarQueryParameter['list_ids'] = listIds;
            }

            if (ownerIds !== undefined) {
                localVarQueryParameter['owner_ids'] = ownerIds;
            }

            if (productUsages !== undefined) {
                localVarQueryParameter['product_usages'] = productUsages;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WeeklySnapshotsApi - functional programming interface
 * @export
 */
export const WeeklySnapshotsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WeeklySnapshotsApiAxiosParamCreator(configuration)
    return {
        /**
         * 영업담당자 목록 조회 (활성 담당자만)
         * @summary Get Owners
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOwnersApiV1WeeklySnapshotsOwnersGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOwnersApiV1WeeklySnapshotsOwnersGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WeeklySnapshotsApi.getOwnersApiV1WeeklySnapshotsOwnersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 스냅샷 데이터가 있는 기업 목록 검색
         * @summary Get Snapshot Companies
         * @param {string | null} [search] 기업명 검색어
         * @param {number} [limit] 최대 결과 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSnapshotCompaniesApiV1WeeklySnapshotsCompaniesGet(search?: string | null, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSnapshotCompaniesApiV1WeeklySnapshotsCompaniesGet(search, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WeeklySnapshotsApi.getSnapshotCompaniesApiV1WeeklySnapshotsCompaniesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 주간 스냅샷 통계 정보
         * @summary Get Snapshot Stats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSnapshotStatsApiV1WeeklySnapshotsStatsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSnapshotStatsApiV1WeeklySnapshotsStatsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WeeklySnapshotsApi.getSnapshotStatsApiV1WeeklySnapshotsStatsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 주간 스냅샷 히트맵 데이터 조회  기업별 주간 스냅샷 점수 데이터를 반환합니다.  - **start_date**: 조회 시작일 (기본: 3개월 전) - **end_date**: 조회 종료일 (기본: 오늘) - **company_ids**: 필터링할 기업 ID (쉼표 구분) - **list_ids**: 필터링할 리스트 ID (쉼표 구분) - **limit**: 최대 조회 기업 수 (기본: 100, 최대: 1000)  Returns:     companies: 기업 목록     weeks: 주차 목록     scores: 기업별 주간 점수 (신규/기존 고객별 마케팅 점수, 세일즈 적합도 점수)
         * @summary Get Weekly Snapshots
         * @param {string | null} [startDate] 시작일 (기본: 3개월 전)
         * @param {string | null} [endDate] 종료일 (기본: 오늘)
         * @param {string | null} [companyIds] 쉼표로 구분된 기업 ID 목록
         * @param {string | null} [listIds] 쉼표로 구분된 리스트 ID 목록 (리스트에 속한 기업만 조회)
         * @param {string | null} [ownerIds] 쉼표로 구분된 영업담당자 ID 목록
         * @param {string | null} [productUsages] 쉼표로 구분된 제품사용 목록 (예: ATS,역량검사,온보딩)
         * @param {number} [limit] 최대 기업 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWeeklySnapshotsApiV1WeeklySnapshotsGet(startDate?: string | null, endDate?: string | null, companyIds?: string | null, listIds?: string | null, ownerIds?: string | null, productUsages?: string | null, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WeeklySnapshotResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWeeklySnapshotsApiV1WeeklySnapshotsGet(startDate, endDate, companyIds, listIds, ownerIds, productUsages, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WeeklySnapshotsApi.getWeeklySnapshotsApiV1WeeklySnapshotsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WeeklySnapshotsApi - factory interface
 * @export
 */
export const WeeklySnapshotsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WeeklySnapshotsApiFp(configuration)
    return {
        /**
         * 영업담당자 목록 조회 (활성 담당자만)
         * @summary Get Owners
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOwnersApiV1WeeklySnapshotsOwnersGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getOwnersApiV1WeeklySnapshotsOwnersGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 스냅샷 데이터가 있는 기업 목록 검색
         * @summary Get Snapshot Companies
         * @param {WeeklySnapshotsApiGetSnapshotCompaniesApiV1WeeklySnapshotsCompaniesGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSnapshotCompaniesApiV1WeeklySnapshotsCompaniesGet(requestParameters: WeeklySnapshotsApiGetSnapshotCompaniesApiV1WeeklySnapshotsCompaniesGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getSnapshotCompaniesApiV1WeeklySnapshotsCompaniesGet(requestParameters.search, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 주간 스냅샷 통계 정보
         * @summary Get Snapshot Stats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSnapshotStatsApiV1WeeklySnapshotsStatsGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.getSnapshotStatsApiV1WeeklySnapshotsStatsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 주간 스냅샷 히트맵 데이터 조회  기업별 주간 스냅샷 점수 데이터를 반환합니다.  - **start_date**: 조회 시작일 (기본: 3개월 전) - **end_date**: 조회 종료일 (기본: 오늘) - **company_ids**: 필터링할 기업 ID (쉼표 구분) - **list_ids**: 필터링할 리스트 ID (쉼표 구분) - **limit**: 최대 조회 기업 수 (기본: 100, 최대: 1000)  Returns:     companies: 기업 목록     weeks: 주차 목록     scores: 기업별 주간 점수 (신규/기존 고객별 마케팅 점수, 세일즈 적합도 점수)
         * @summary Get Weekly Snapshots
         * @param {WeeklySnapshotsApiGetWeeklySnapshotsApiV1WeeklySnapshotsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWeeklySnapshotsApiV1WeeklySnapshotsGet(requestParameters: WeeklySnapshotsApiGetWeeklySnapshotsApiV1WeeklySnapshotsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<WeeklySnapshotResponse> {
            return localVarFp.getWeeklySnapshotsApiV1WeeklySnapshotsGet(requestParameters.startDate, requestParameters.endDate, requestParameters.companyIds, requestParameters.listIds, requestParameters.ownerIds, requestParameters.productUsages, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getSnapshotCompaniesApiV1WeeklySnapshotsCompaniesGet operation in WeeklySnapshotsApi.
 * @export
 * @interface WeeklySnapshotsApiGetSnapshotCompaniesApiV1WeeklySnapshotsCompaniesGetRequest
 */
export interface WeeklySnapshotsApiGetSnapshotCompaniesApiV1WeeklySnapshotsCompaniesGetRequest {
    /**
     * 기업명 검색어
     * @type {string}
     * @memberof WeeklySnapshotsApiGetSnapshotCompaniesApiV1WeeklySnapshotsCompaniesGet
     */
    readonly search?: string | null

    /**
     * 최대 결과 수
     * @type {number}
     * @memberof WeeklySnapshotsApiGetSnapshotCompaniesApiV1WeeklySnapshotsCompaniesGet
     */
    readonly limit?: number
}

/**
 * Request parameters for getWeeklySnapshotsApiV1WeeklySnapshotsGet operation in WeeklySnapshotsApi.
 * @export
 * @interface WeeklySnapshotsApiGetWeeklySnapshotsApiV1WeeklySnapshotsGetRequest
 */
export interface WeeklySnapshotsApiGetWeeklySnapshotsApiV1WeeklySnapshotsGetRequest {
    /**
     * 시작일 (기본: 3개월 전)
     * @type {string}
     * @memberof WeeklySnapshotsApiGetWeeklySnapshotsApiV1WeeklySnapshotsGet
     */
    readonly startDate?: string | null

    /**
     * 종료일 (기본: 오늘)
     * @type {string}
     * @memberof WeeklySnapshotsApiGetWeeklySnapshotsApiV1WeeklySnapshotsGet
     */
    readonly endDate?: string | null

    /**
     * 쉼표로 구분된 기업 ID 목록
     * @type {string}
     * @memberof WeeklySnapshotsApiGetWeeklySnapshotsApiV1WeeklySnapshotsGet
     */
    readonly companyIds?: string | null

    /**
     * 쉼표로 구분된 리스트 ID 목록 (리스트에 속한 기업만 조회)
     * @type {string}
     * @memberof WeeklySnapshotsApiGetWeeklySnapshotsApiV1WeeklySnapshotsGet
     */
    readonly listIds?: string | null

    /**
     * 쉼표로 구분된 영업담당자 ID 목록
     * @type {string}
     * @memberof WeeklySnapshotsApiGetWeeklySnapshotsApiV1WeeklySnapshotsGet
     */
    readonly ownerIds?: string | null

    /**
     * 쉼표로 구분된 제품사용 목록 (예: ATS,역량검사,온보딩)
     * @type {string}
     * @memberof WeeklySnapshotsApiGetWeeklySnapshotsApiV1WeeklySnapshotsGet
     */
    readonly productUsages?: string | null

    /**
     * 최대 기업 수
     * @type {number}
     * @memberof WeeklySnapshotsApiGetWeeklySnapshotsApiV1WeeklySnapshotsGet
     */
    readonly limit?: number
}

/**
 * WeeklySnapshotsApi - object-oriented interface
 * @export
 * @class WeeklySnapshotsApi
 * @extends {BaseAPI}
 */
export class WeeklySnapshotsApi extends BaseAPI {
    /**
     * 영업담당자 목록 조회 (활성 담당자만)
     * @summary Get Owners
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeeklySnapshotsApi
     */
    public getOwnersApiV1WeeklySnapshotsOwnersGet(options?: RawAxiosRequestConfig) {
        return WeeklySnapshotsApiFp(this.configuration).getOwnersApiV1WeeklySnapshotsOwnersGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 스냅샷 데이터가 있는 기업 목록 검색
     * @summary Get Snapshot Companies
     * @param {WeeklySnapshotsApiGetSnapshotCompaniesApiV1WeeklySnapshotsCompaniesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeeklySnapshotsApi
     */
    public getSnapshotCompaniesApiV1WeeklySnapshotsCompaniesGet(requestParameters: WeeklySnapshotsApiGetSnapshotCompaniesApiV1WeeklySnapshotsCompaniesGetRequest = {}, options?: RawAxiosRequestConfig) {
        return WeeklySnapshotsApiFp(this.configuration).getSnapshotCompaniesApiV1WeeklySnapshotsCompaniesGet(requestParameters.search, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 주간 스냅샷 통계 정보
     * @summary Get Snapshot Stats
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeeklySnapshotsApi
     */
    public getSnapshotStatsApiV1WeeklySnapshotsStatsGet(options?: RawAxiosRequestConfig) {
        return WeeklySnapshotsApiFp(this.configuration).getSnapshotStatsApiV1WeeklySnapshotsStatsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 주간 스냅샷 히트맵 데이터 조회  기업별 주간 스냅샷 점수 데이터를 반환합니다.  - **start_date**: 조회 시작일 (기본: 3개월 전) - **end_date**: 조회 종료일 (기본: 오늘) - **company_ids**: 필터링할 기업 ID (쉼표 구분) - **list_ids**: 필터링할 리스트 ID (쉼표 구분) - **limit**: 최대 조회 기업 수 (기본: 100, 최대: 1000)  Returns:     companies: 기업 목록     weeks: 주차 목록     scores: 기업별 주간 점수 (신규/기존 고객별 마케팅 점수, 세일즈 적합도 점수)
     * @summary Get Weekly Snapshots
     * @param {WeeklySnapshotsApiGetWeeklySnapshotsApiV1WeeklySnapshotsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeeklySnapshotsApi
     */
    public getWeeklySnapshotsApiV1WeeklySnapshotsGet(requestParameters: WeeklySnapshotsApiGetWeeklySnapshotsApiV1WeeklySnapshotsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return WeeklySnapshotsApiFp(this.configuration).getWeeklySnapshotsApiV1WeeklySnapshotsGet(requestParameters.startDate, requestParameters.endDate, requestParameters.companyIds, requestParameters.listIds, requestParameters.ownerIds, requestParameters.productUsages, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }
}

