/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PossibilityType } from './possibility-type';

/**
 * 액션 수행 시점의 상태
 * @export
 * @interface ActionState
 */
export interface ActionState {
    /**
     * 
     * @type {PossibilityType}
     * @memberof ActionState
     */
    'possibility'?: PossibilityType;
    /**
     * 
     * @type {number}
     * @memberof ActionState
     */
    'targetRevenue'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ActionState
     */
    'targetDate'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ActionState
     */
    'test'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ActionState
     */
    'quote'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ActionState
     */
    'approval'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ActionState
     */
    'contract'?: boolean;
}



