/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 기업 정보
 * @export
 * @interface AppsDashboardApiModelsWeeklySnapshotCompany
 */
export interface AppsDashboardApiModelsWeeklySnapshotCompany {
    /**
     * 
     * @type {string}
     * @memberof AppsDashboardApiModelsWeeklySnapshotCompany
     */
    'company_id': string;
    /**
     * 
     * @type {string}
     * @memberof AppsDashboardApiModelsWeeklySnapshotCompany
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppsDashboardApiModelsWeeklySnapshotCompany
     */
    'company_size'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppsDashboardApiModelsWeeklySnapshotCompany
     */
    'segment'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppsDashboardApiModelsWeeklySnapshotCompany
     */
    'hubspot_owner_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppsDashboardApiModelsWeeklySnapshotCompany
     */
    'owner_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppsDashboardApiModelsWeeklySnapshotCompany
     */
    'product_usage'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppsDashboardApiModelsWeeklySnapshotCompany
     */
    'renewal_date'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AppsDashboardApiModelsWeeklySnapshotCompany
     */
    'contract_amount'?: number | null;
}

