/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 마케팅 이벤트 정보
 * @export
 * @interface AppsDashboardApiModelsWeeklySnapshotMarketingEvent
 */
export interface AppsDashboardApiModelsWeeklySnapshotMarketingEvent {
    /**
     * 
     * @type {string}
     * @memberof AppsDashboardApiModelsWeeklySnapshotMarketingEvent
     */
    'event_id': string;
    /**
     * 
     * @type {string}
     * @memberof AppsDashboardApiModelsWeeklySnapshotMarketingEvent
     */
    'event_name': string;
    /**
     * 
     * @type {string}
     * @memberof AppsDashboardApiModelsWeeklySnapshotMarketingEvent
     */
    'event_type'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppsDashboardApiModelsWeeklySnapshotMarketingEvent
     */
    'start_datetime'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppsDashboardApiModelsWeeklySnapshotMarketingEvent
     */
    'year_week'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AppsDashboardApiModelsWeeklySnapshotMarketingEvent
     */
    'total_attendees'?: number;
}

