/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 기업 규모 (BigQuery companies.company_size 값과 일치)
 * @export
 * @enum {string}
 */

export const CompanySize = {
    T0: 'T0',
    T1: 'T1',
    T2: 'T2',
    T3: 'T3',
    T4: 'T4',
    T5: 'T5',
    T10: 'T10',
    UNKNOWN: 'UNKNOWN'
} as const;

export type CompanySize = typeof CompanySize[keyof typeof CompanySize];



