/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 콘텐츠 중분류
 * @export
 * @enum {string}
 */

export const ContentSubCategory = {
    TOFU: 'TOFU',
    MOFU: 'MOFU',
    BOFU: 'BOFU',
    PEOPLE_MANAGEMENT: 'PEOPLE_MANAGEMENT',
    CLASS: 'CLASS',
    PODCAST: 'PODCAST',
    INSIGHT: 'INSIGHT',
    NEWSLETTER_INSA: 'NEWSLETTER_INSA',
    NEWSLETTER_PEOPLE: 'NEWSLETTER_PEOPLE',
    PROMO_EMAIL: 'PROMO_EMAIL',
    OTHER_EMAIL: 'OTHER_EMAIL',
    MAIN_PAGE: 'MAIN_PAGE',
    TRIAL: 'TRIAL',
    BROCHURE: 'BROCHURE',
    INQUIRY: 'INQUIRY',
    SOLUTION_PAGE: 'SOLUTION_PAGE',
    MBM_EVENT: 'MBM_EVENT',
    OTHER: 'OTHER'
} as const;

export type ContentSubCategory = typeof ContentSubCategory[keyof typeof ContentSubCategory];



