/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 액션 타입
 * @export
 * @enum {string}
 */

export const ContentActionType = {
    PAGE_VISITED: 'PAGE_VISITED',
    FORM_SUBMISSION: 'FORM_SUBMISSION',
    OPENED_EMAIL: 'OPENED_EMAIL',
    CLICKED_LINK: 'CLICKED_LINK',
    REGISTERED: 'REGISTERED',
    ATTENDED: 'ATTENDED',
    NPS_SUBMITTED: 'NPS_SUBMITTED'
} as const;

export type ContentActionType = typeof ContentActionType[keyof typeof ContentActionType];



