/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 콘텐츠 대분류
 * @export
 * @enum {string}
 */

export const ContentMainCategory = {
    ARTICLE: 'ARTICLE',
    REPORT: 'REPORT',
    ON_AIR: 'ON_AIR',
    TOOLS: 'TOOLS',
    TOOLS_PLUS: 'TOOLS_PLUS',
    PLANNER: 'PLANNER',
    EDM: 'EDM',
    MBM: 'MBM',
    ETC: 'ETC'
} as const;

export type ContentMainCategory = typeof ContentMainCategory[keyof typeof ContentMainCategory];



