/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AmountRange } from './amount-range';
// May contain unused imports in some cases
// @ts-ignore
import type { Category } from './category';
// May contain unused imports in some cases
// @ts-ignore
import type { CompanySize } from './company-size';
// May contain unused imports in some cases
// @ts-ignore
import type { DateRangeFilter } from './date-range-filter';
// May contain unused imports in some cases
// @ts-ignore
import type { PossibilityRange } from './possibility-range';
// May contain unused imports in some cases
// @ts-ignore
import type { ProductType } from './product-type';
// May contain unused imports in some cases
// @ts-ignore
import type { ProgressStage } from './progress-stage';

/**
 * 대시보드 필터
 * @export
 * @interface DashboardFilters
 */
export interface DashboardFilters {
    /**
     * 
     * @type {Array<CompanySize>}
     * @memberof DashboardFilters
     */
    'companySizes'?: Array<CompanySize> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof DashboardFilters
     */
    'managers'?: Array<string> | null;
    /**
     * 
     * @type {Array<Category>}
     * @memberof DashboardFilters
     */
    'categories'?: Array<Category> | null;
    /**
     * 
     * @type {Array<ProductType>}
     * @memberof DashboardFilters
     */
    'productUsages'?: Array<ProductType> | null;
    /**
     * 
     * @type {PossibilityRange}
     * @memberof DashboardFilters
     */
    'possibilityRange'?: PossibilityRange | null;
    /**
     * 
     * @type {Array<ProgressStage>}
     * @memberof DashboardFilters
     */
    'stages'?: Array<ProgressStage> | null;
    /**
     * 
     * @type {AmountRange}
     * @memberof DashboardFilters
     */
    'contractAmountRange'?: AmountRange | null;
    /**
     * 
     * @type {AmountRange}
     * @memberof DashboardFilters
     */
    'targetRevenueRange'?: AmountRange | null;
    /**
     * 
     * @type {AmountRange}
     * @memberof DashboardFilters
     */
    'expectedRevenueRange'?: AmountRange | null;
    /**
     * 
     * @type {DateRangeFilter}
     * @memberof DashboardFilters
     */
    'targetMonthRange'?: DateRangeFilter | null;
    /**
     * 
     * @type {DateRangeFilter}
     * @memberof DashboardFilters
     */
    'lastContactDateRange'?: DateRangeFilter | null;
}

