/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Category } from './category';
// May contain unused imports in some cases
// @ts-ignore
import type { CompanySize } from './company-size';
// May contain unused imports in some cases
// @ts-ignore
import type { PeriodData } from './period-data';
// May contain unused imports in some cases
// @ts-ignore
import type { ProductType } from './product-type';

/**
 * 대시보드 테이블 행
 * @export
 * @interface DashboardTableRow
 */
export interface DashboardTableRow {
    /**
     * 
     * @type {number}
     * @memberof DashboardTableRow
     */
    'companyId': number;
    /**
     * 
     * @type {string}
     * @memberof DashboardTableRow
     */
    'companyName': string;
    /**
     * 
     * @type {CompanySize}
     * @memberof DashboardTableRow
     */
    'companySize'?: CompanySize | null;
    /**
     * 
     * @type {Category}
     * @memberof DashboardTableRow
     */
    'category'?: Category | null;
    /**
     * 
     * @type {Array<ProductType>}
     * @memberof DashboardTableRow
     */
    'productUsage'?: Array<ProductType>;
    /**
     * 
     * @type {string}
     * @memberof DashboardTableRow
     */
    'manager'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DashboardTableRow
     */
    'contractAmount'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DashboardTableRow
     */
    'lastMBMDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DashboardTableRow
     */
    'lastContactDate'?: string | null;
    /**
     * 
     * @type {PeriodData}
     * @memberof DashboardTableRow
     */
    'current': PeriodData;
    /**
     * 
     * @type {PeriodData}
     * @memberof DashboardTableRow
     */
    'previous': PeriodData;
}



