/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Engagement Item - 이벤트 기반 활동 (콘텐츠)
 * @export
 * @interface EngagementItem
 */
export interface EngagementItem {
    /**
     * 
     * @type {string}
     * @memberof EngagementItem
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof EngagementItem
     */
    'latestViewDate': string;
    /**
     * 
     * @type {string}
     * @memberof EngagementItem
     */
    'funnelType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EngagementItem
     */
    'contentType'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EngagementItem
     */
    'viewCount'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof EngagementItem
     */
    'url'?: string | null;
}

