/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContentActionType } from './content-action-type';

/**
 * Engagement Item - 이벤트 기반 활동
 * @export
 * @interface EngagementItem
 */
export interface EngagementItem {
    /**
     * 
     * @type {string}
     * @memberof EngagementItem
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof EngagementItem
     */
    'date': string;
    /**
     * 
     * @type {string}
     * @memberof EngagementItem
     */
    'url'?: string | null;
    /**
     * 
     * @type {ContentActionType}
     * @memberof EngagementItem
     */
    'actionType': ContentActionType;
    /**
     * 
     * @type {string}
     * @memberof EngagementItem
     */
    'introducedProduct'?: string | null;
}



