/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContentActionType } from './content-action-type';
// May contain unused imports in some cases
// @ts-ignore
import type { ContentMainCategory } from './content-main-category';
// May contain unused imports in some cases
// @ts-ignore
import type { ContentSubCategory } from './content-sub-category';

/**
 * Engagement Score - 이벤트 기반 활동
 * @export
 * @interface EngagementScore
 */
export interface EngagementScore {
    /**
     * 
     * @type {string}
     * @memberof EngagementScore
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof EngagementScore
     */
    'date': string;
    /**
     * 
     * @type {ContentMainCategory}
     * @memberof EngagementScore
     */
    'mainCategory': ContentMainCategory;
    /**
     * 
     * @type {ContentSubCategory}
     * @memberof EngagementScore
     */
    'subCategory': ContentSubCategory;
    /**
     * 
     * @type {ContentActionType}
     * @memberof EngagementScore
     */
    'action': ContentActionType;
    /**
     * 
     * @type {number}
     * @memberof EngagementScore
     */
    'score': number;
    /**
     * 
     * @type {string}
     * @memberof EngagementScore
     */
    'url'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EngagementScore
     */
    'website'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EngagementScore
     */
    'introducedProduct'?: string | null;
}



