/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 기업별 이벤트 참석
 * @export
 * @interface EventAttendance
 */
export interface EventAttendance {
    /**
     * 
     * @type {string}
     * @memberof EventAttendance
     */
    'company_id': string;
    /**
     * 
     * @type {string}
     * @memberof EventAttendance
     */
    'event_id': string;
    /**
     * 
     * @type {number}
     * @memberof EventAttendance
     */
    'attendee_count'?: number;
}

