/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FitScoreType } from './fit-score-type';

/**
 * Fit Score - 속성 기반 점수
 * @export
 * @interface FitScore
 */
export interface FitScore {
    /**
     * 
     * @type {FitScoreType}
     * @memberof FitScore
     */
    'type': FitScoreType;
    /**
     * 
     * @type {string}
     * @memberof FitScore
     */
    'date': string;
    /**
     * 
     * @type {number}
     * @memberof FitScore
     */
    'score': number;
    /**
     * 
     * @type {string}
     * @memberof FitScore
     */
    'description'?: string | null;
}



