/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Company } from './company';
// May contain unused imports in some cases
// @ts-ignore
import type { EventAttendance } from './event-attendance';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelsHeatmapMarketingEvent } from './models-heatmap-marketing-event';
// May contain unused imports in some cases
// @ts-ignore
import type { TrustScore } from './trust-score';
// May contain unused imports in some cases
// @ts-ignore
import type { Week } from './week';

/**
 * 히트맵 API 응답
 * @export
 * @interface HeatmapResponse
 */
export interface HeatmapResponse {
    /**
     * 
     * @type {Array<Company>}
     * @memberof HeatmapResponse
     */
    'companies': Array<Company>;
    /**
     * 
     * @type {Array<Week>}
     * @memberof HeatmapResponse
     */
    'weeks': Array<Week>;
    /**
     * 
     * @type {Array<TrustScore>}
     * @memberof HeatmapResponse
     */
    'scores': Array<TrustScore>;
    /**
     * 
     * @type {Array<ModelsHeatmapMarketingEvent>}
     * @memberof HeatmapResponse
     */
    'events': Array<ModelsHeatmapMarketingEvent>;
    /**
     * 
     * @type {Array<EventAttendance>}
     * @memberof HeatmapResponse
     */
    'attendance': Array<EventAttendance>;
}

