/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AppsDashboardApiModelsHeatmapCompany } from './apps-dashboard-api-models-heatmap-company';
// May contain unused imports in some cases
// @ts-ignore
import type { AppsDashboardApiModelsHeatmapEventAttendance } from './apps-dashboard-api-models-heatmap-event-attendance';
// May contain unused imports in some cases
// @ts-ignore
import type { AppsDashboardApiModelsHeatmapMarketingEvent } from './apps-dashboard-api-models-heatmap-marketing-event';
// May contain unused imports in some cases
// @ts-ignore
import type { AppsDashboardApiModelsWeeklySnapshotWeek } from './apps-dashboard-api-models-weekly-snapshot-week';
// May contain unused imports in some cases
// @ts-ignore
import type { TrustScore } from './trust-score';

/**
 * 히트맵 API 응답
 * @export
 * @interface HeatmapResponse
 */
export interface HeatmapResponse {
    /**
     * 
     * @type {Array<AppsDashboardApiModelsHeatmapCompany>}
     * @memberof HeatmapResponse
     */
    'companies': Array<AppsDashboardApiModelsHeatmapCompany>;
    /**
     * 
     * @type {Array<AppsDashboardApiModelsWeeklySnapshotWeek>}
     * @memberof HeatmapResponse
     */
    'weeks': Array<AppsDashboardApiModelsWeeklySnapshotWeek>;
    /**
     * 
     * @type {Array<TrustScore>}
     * @memberof HeatmapResponse
     */
    'scores': Array<TrustScore>;
    /**
     * 
     * @type {Array<AppsDashboardApiModelsHeatmapMarketingEvent>}
     * @memberof HeatmapResponse
     */
    'events': Array<AppsDashboardApiModelsHeatmapMarketingEvent>;
    /**
     * 
     * @type {Array<AppsDashboardApiModelsHeatmapEventAttendance>}
     * @memberof HeatmapResponse
     */
    'attendance': Array<AppsDashboardApiModelsHeatmapEventAttendance>;
}

