/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 영업담당자별 기업 수
 * @export
 * @interface OwnerCount
 */
export interface OwnerCount {
    /**
     * 
     * @type {string}
     * @memberof OwnerCount
     */
    'owner_id': string;
    /**
     * 
     * @type {number}
     * @memberof OwnerCount
     */
    'count': number;
}

