/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 페이지네이션 설정
 * @export
 * @interface PaginationConfig
 */
export interface PaginationConfig {
    /**
     * 
     * @type {number}
     * @memberof PaginationConfig
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationConfig
     */
    'pageSize'?: number;
}

