/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 시점별 데이터 (현재/과거 공통)
 * @export
 * @interface PeriodData
 */
export interface PeriodData {
    /**
     * 
     * @type {number}
     * @memberof PeriodData
     */
    'trustIndex'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PeriodData
     */
    'possibility'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PeriodData
     */
    'targetRevenue'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PeriodData
     */
    'expectedRevenue'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PeriodData
     */
    'targetMonth'?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof PeriodData
     */
    'test'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PeriodData
     */
    'quote'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PeriodData
     */
    'approval'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PeriodData
     */
    'contract'?: boolean;
}

