/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 제품 타입
 * @export
 * @enum {string}
 */

export const ProductType = {
    ATS: 'ATS',
    SR: '역검SR',
    INHR: 'INHR+통합',
    : '역검',
    2: '이탈사'
} as const;

export type ProductType = typeof ProductType[keyof typeof ProductType];



