/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 영업 활동 유형
 * @export
 * @enum {string}
 */

export const SalesActionType = {
    CALL: 'CALL',
    MEETING: 'MEETING',
    EMAIL: 'EMAIL'
} as const;

export type SalesActionType = typeof SalesActionType[keyof typeof SalesActionType];



