/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SalesActionType } from './sales-action-type';
// May contain unused imports in some cases
// @ts-ignore
import type { StateChange } from './state-change';

/**
 * 영업 액션
 * @export
 * @interface SalesAction
 */
export interface SalesAction {
    /**
     * 
     * @type {number}
     * @memberof SalesAction
     */
    'actionId'?: number | null;
    /**
     * 
     * @type {SalesActionType}
     * @memberof SalesAction
     */
    'type': SalesActionType;
    /**
     * 
     * @type {string}
     * @memberof SalesAction
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof SalesAction
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof SalesAction
     */
    'date': string;
    /**
     * 
     * @type {StateChange}
     * @memberof SalesAction
     */
    'stateChange'?: StateChange | null;
}



