/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 정렬 설정
 * @export
 * @interface SortConfig
 */
export interface SortConfig {
    /**
     * 
     * @type {string}
     * @memberof SortConfig
     */
    'field': SortConfigFieldEnum;
    /**
     * 
     * @type {string}
     * @memberof SortConfig
     */
    'order'?: SortConfigOrderEnum;
}

export const SortConfigFieldEnum = {
    COMPANY_NAME: 'companyName',
    COMPANY_SIZE: 'companySize',
    MANAGER: 'manager',
    CATEGORY: 'category',
    PRODUCT_USAGE: 'productUsage',
    TRUST_INDEX: 'trustIndex',
    CONTRACT_AMOUNT: 'contractAmount',
    TARGET_REVENUE: 'targetRevenue',
    POSSIBILITY: 'possibility',
    EXPECTED_REVENUE: 'expectedRevenue',
    TARGET_DATE: 'targetDate',
    LAST_CONTACT_DATE: 'lastContactDate',
    LAST_MBM_DATE: 'lastMBMDate'
} as const;

export type SortConfigFieldEnum = typeof SortConfigFieldEnum[keyof typeof SortConfigFieldEnum];
export const SortConfigOrderEnum = {
    ASC: 'asc',
    DESC: 'desc'
} as const;

export type SortConfigOrderEnum = typeof SortConfigOrderEnum[keyof typeof SortConfigOrderEnum];


