/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ActionState } from './action-state';

/**
 * 액션으로 인한 상태 변화
 * @export
 * @interface StateChange
 */
export interface StateChange {
    /**
     * 
     * @type {ActionState}
     * @memberof StateChange
     */
    'before': ActionState;
    /**
     * 
     * @type {ActionState}
     * @memberof StateChange
     */
    'after': ActionState;
}

