/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 기간 필터
 * @export
 * @enum {string}
 */

export const TimePeriod = {
    WEEK: 'WEEK',
    MONTH: 'MONTH',
    HALF_YEAR: 'HALF_YEAR',
    YEAR: 'YEAR'
} as const;

export type TimePeriod = typeof TimePeriod[keyof typeof TimePeriod];



