/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OwnerCount } from './owner-count';

/**
 * 필터 카운트용 총 기업 수 (limit 없이)
 * @export
 * @interface TotalCounts
 */
export interface TotalCounts {
    /**
     * 
     * @type {number}
     * @memberof TotalCounts
     */
    'total_companies': number;
    /**
     * 
     * @type {Array<OwnerCount>}
     * @memberof TotalCounts
     */
    'by_owner'?: Array<OwnerCount>;
}

