/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 신뢰 레벨 (P1/P2/P3)
 * @export
 * @enum {string}
 */

export const TrustLevel = {
    P1: 'P1',
    P2: 'P2',
    P3: 'P3'
} as const;

export type TrustLevel = typeof TrustLevel[keyof typeof TrustLevel];



