/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EngagementItem } from './engagement-item';

/**
 * 신뢰지수 변동 상세 응답
 * @export
 * @interface TrustChangeDetailResponse
 */
export interface TrustChangeDetailResponse {
    /**
     * 
     * @type {number}
     * @memberof TrustChangeDetailResponse
     */
    'changeAmount': number;
    /**
     * 
     * @type {Array<EngagementItem>}
     * @memberof TrustChangeDetailResponse
     */
    'engagementItems': Array<EngagementItem>;
    /**
     * 
     * @type {string}
     * @memberof TrustChangeDetailResponse
     */
    'hubspotUrl': string;
}

