/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Category } from './category';
// May contain unused imports in some cases
// @ts-ignore
import type { CompanySize } from './company-size';

/**
 * 신뢰지수 변동 항목
 * @export
 * @interface TrustChangeItem
 */
export interface TrustChangeItem {
    /**
     * 
     * @type {number}
     * @memberof TrustChangeItem
     */
    'companyId': number;
    /**
     * 
     * @type {string}
     * @memberof TrustChangeItem
     */
    'companyName': string;
    /**
     * 
     * @type {string}
     * @memberof TrustChangeItem
     */
    'manager'?: string | null;
    /**
     * 
     * @type {Category}
     * @memberof TrustChangeItem
     */
    'category'?: Category | null;
    /**
     * 
     * @type {CompanySize}
     * @memberof TrustChangeItem
     */
    'companySize'?: CompanySize | null;
    /**
     * 
     * @type {number}
     * @memberof TrustChangeItem
     */
    'pastTrustIndex'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TrustChangeItem
     */
    'currentTrustIndex'?: number | null;
}



