/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 신뢰 점수 데이터
 * @export
 * @interface TrustScore
 */
export interface TrustScore {
    /**
     * 
     * @type {string}
     * @memberof TrustScore
     */
    'company_id': string;
    /**
     * 
     * @type {string}
     * @memberof TrustScore
     */
    'year_week': string;
    /**
     * 
     * @type {number}
     * @memberof TrustScore
     */
    'avg_score'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TrustScore
     */
    'max_score'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TrustScore
     */
    'min_score'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TrustScore
     */
    'lead_count'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TrustScore
     */
    'is_before_deal'?: boolean;
}

