/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TrustChangeItem } from './trust-change-item';

/**
 * 신뢰지수 카드 응답
 * @export
 * @interface TrustIndexCardResponse
 */
export interface TrustIndexCardResponse {
    /**
     * 
     * @type {Array<TrustChangeItem>}
     * @memberof TrustIndexCardResponse
     */
    'trustUp': Array<TrustChangeItem>;
    /**
     * 
     * @type {Array<TrustChangeItem>}
     * @memberof TrustIndexCardResponse
     */
    'trustDown': Array<TrustChangeItem>;
}

