/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 주차 정보
 * @export
 * @interface Week
 */
export interface Week {
    /**
     * 
     * @type {string}
     * @memberof Week
     */
    'year_week': string;
    /**
     * 
     * @type {string}
     * @memberof Week
     */
    'start_date': string;
    /**
     * 
     * @type {string}
     * @memberof Week
     */
    'end_date': string;
}

