/* tslint:disable */
/* eslint-disable */
/**
 * Trust Score Dashboard API
 * 기업별 신뢰 점수 시계열 데이터 API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AppsDashboardApiModelsWeeklySnapshotCompany } from './apps-dashboard-api-models-weekly-snapshot-company';
// May contain unused imports in some cases
// @ts-ignore
import type { AppsDashboardApiModelsWeeklySnapshotEventAttendance } from './apps-dashboard-api-models-weekly-snapshot-event-attendance';
// May contain unused imports in some cases
// @ts-ignore
import type { AppsDashboardApiModelsWeeklySnapshotMarketingEvent } from './apps-dashboard-api-models-weekly-snapshot-marketing-event';
// May contain unused imports in some cases
// @ts-ignore
import type { AppsDashboardApiModelsWeeklySnapshotWeek } from './apps-dashboard-api-models-weekly-snapshot-week';
// May contain unused imports in some cases
// @ts-ignore
import type { CompanyWeeklyScore } from './company-weekly-score';
// May contain unused imports in some cases
// @ts-ignore
import type { TotalCounts } from './total-counts';

/**
 * Weekly Snapshot 히트맵 API 응답
 * @export
 * @interface WeeklySnapshotResponse
 */
export interface WeeklySnapshotResponse {
    /**
     * 
     * @type {Array<AppsDashboardApiModelsWeeklySnapshotCompany>}
     * @memberof WeeklySnapshotResponse
     */
    'companies': Array<AppsDashboardApiModelsWeeklySnapshotCompany>;
    /**
     * 
     * @type {Array<AppsDashboardApiModelsWeeklySnapshotWeek>}
     * @memberof WeeklySnapshotResponse
     */
    'weeks': Array<AppsDashboardApiModelsWeeklySnapshotWeek>;
    /**
     * 
     * @type {Array<CompanyWeeklyScore>}
     * @memberof WeeklySnapshotResponse
     */
    'scores': Array<CompanyWeeklyScore>;
    /**
     * 
     * @type {Array<AppsDashboardApiModelsWeeklySnapshotMarketingEvent>}
     * @memberof WeeklySnapshotResponse
     */
    'events'?: Array<AppsDashboardApiModelsWeeklySnapshotMarketingEvent>;
    /**
     * 
     * @type {Array<AppsDashboardApiModelsWeeklySnapshotEventAttendance>}
     * @memberof WeeklySnapshotResponse
     */
    'attendance'?: Array<AppsDashboardApiModelsWeeklySnapshotEventAttendance>;
    /**
     * 
     * @type {TotalCounts}
     * @memberof WeeklySnapshotResponse
     */
    'total_counts'?: TotalCounts | null;
}

